- pgcli/main.py
I'm a distro packager and the generated /usr/bin/pgcli doesn't work for me and I need more control. I need my own entry point so I can execute the module using python -m pgcli.main.
> Add entry point

- setup.py
Because it uses click.termui.secho() with the keyword argument 'err' that has
been added in click 3.2.
Fixes #54
> click version must be >= 3.2

- .travis.yml
- tests/tox.ini
- tox.ini
Current version of pgcli runs tests too many times in travis, total 12 times instead of 4.
Example: https://travis-ci.org/amjith/pgcli/builds/46215230
Idea for the solution was taken from https://github.com/eventlet/eventlet/blob/master/.travis.yml
> Travis - run tox only once per python version

- pgcli/packages/sqlcompletion.py
This commit fixes a crash in autocompletion, when a comma character is entered before any valid sql keyword, e.g., 
```
database_name> asd,Exception in thread Thread-309:
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/__init__.py", line 466, in run
CompleteEvent(text_inserted=True)))
File "/usr/local/lib/python2.7/dist-packages/pgcli/pgcompleter.py", line 92, in get_completions
document.text_before_cursor)
File "/usr/local/lib/python2.7/dist-packages/pgcli/packages/sqlcompletion.py", line 46, in suggest_type
return suggest_based_on_last_token(last_token, …
```
> Fix a crash in autocompletion

- pgcli/main.py
- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
this patch supports table and column names that have space, special chars, non-ascii word characters and names that conflict with build in function names and keywords.
It also fixes a minor issue where the table columns where not refreshed because of a case-sensitive comparison of the tokens.
For example the following tables/columns can be autocompleted with this patch:
```sql
CREATE TABLE "CamelCase" (
"has space" text,
"has %^$&" text,
"φρόνησις" text,
"MIN" text,
"DROP" text,
"CamelCase" text
);
CREATE TABLE "foo bar" (
"has space" text,
"has %^$&" text,
"φρόνησις" text,
"MIN" text,
"DROP" text,
"CamelCase" text
);
CREATE TABLE "foo *@#^!$" (
"has space" text,
"has %^$&" text,
"φρόνησις" text,
"MIN" text,
"DROP" text,
"CamelCase" text
);
CREATE TABLE "εὐδαιμονία" (
"has space" text, …
```
> support for table/column names which should be escaped

- .travis.yml
- pgcli/packages/expanded.py
- tests/pytest.ini
- tests/test_pgexecute.py
- tox.ini
PR #71 introduced a bug, where the python version that was used by travis did not match the version intended.
Also fix the problems plaguing current master builds failing under python 3, with tests! :)
@amjith
> Fix travis and build errors under python 3.

- .gitignore
- pgcli/main.py
Hi,
On Linux, with Python 3.4.2 and psycopg2 2.5.4, I have this error when I try to connect to a database with a password:
<pre>(pyvenv) lg@steroids:~/Documents/IDEA/LGbo$ pgcli -h localhost -p 5432 -U asterisk asterisk
'OperationalError' object has no attribute 'message'</pre>
With this commit, I have no more issues.
I've quickly tested with Python 2.7.6, it continues to work.
Regards.
> Fix auto passwd prompt

- pgcli/main.py
file handler was attached to the pgcli.main logger instead of pgcli
> fix logging bug: log statements outside pgcli.main not logged to file

- pgcli/magic.py
- pgcli/main.py
`%pgcli` magic now persists pgcli objects by stashing them in sql-magic connection objects. after first connecting with `%pgcli postgresql://blahblahblah` you can return to that same connection with simply `%pgcli`. if you have multuple pgcli connections open, you can refer to them with an alias like `%pgcli username@dbname`
also, mutating queries aren't rerun in sql magic
> ipython magic improvements

- pgcli/pgexecute.py
- tests/test_pgexecute.py
In the current version of pgcli, `bytea` fields trigger Unicode decode errors when queried:
_test_db> CREATE TABLE binarydata(c bytea) 
CREATE TABLE
_test_db> INSERT INTO binarydata VALUES (decode('DEADBEEF', 'hex'))
INSERT 0 1
_test_db> SELECT * FROM binarydata
'ascii' codec can't decode byte 0xde in position 0: ordinal not in range(128)
_test_db> 
Casting the field to a string for display allows tables with `bytea` fields to be queried as expected. This pull request adds a type converter to have psycopg2 automatically perform the conversion on all `bytea` fields:
_test_db> SELECT * FROM binarydata
+------------+
| c          |
|------------|
| \xdeadbeef |
+------------+
SELECT 1
_test_db>
> Cast bytea fields to text for output.

- pgcli/main.py
I've been slowly working on a pgcli autocompletion plugin for Sublime Text 3, and found myself importing and copy/pasting a little more than I'd like. This PR simply moves pgcompleter construction to PGCli.__init__, and adds a convenience method PGCli.get_completions(text, cursor_position) which delegates to self.completer.get_completions.
> Minor PGCli API improvements

- pgcli/main.py
- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- setup.py
- tests/test_parseutils.py
- tests/test_pgexecute.py
- tests/test_pgspecial.py
- tests/test_smart_completion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
- tests/utils.py
This PR would fix #22, and also I think #39 as a side-effect
Issues:
* I used pandas DataFrames for working with database metadata -- I found them a lot more flexible than a pure standard lib dict/list based approach. But I'm not sure how you'd feel about adding pandas as a requirement.
* We don't have any tests for "DoubleQuoted" identifiers -- I'm not confident I didn't break that.
> Make autocomplete schema-aware

- pgcli/pgcompleter.py
- pgcli/pgexecute.py
pgcli crashed for me today after making a new schema:
```
File "C:\Users\dg\Anaconda3\envs\pgcli2\Scripts\pgcli-script.py", line 9, in <module>
load_entry_point('pgcli==0.15.2', 'console_scripts', 'pgcli')()
File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 610, in __call__
return self.main(*args, **kwargs)
File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 590, in main
rv = self.invoke(ctx)
File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 782, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 416, in invoke
return callback(*args, **kwargs)
File "c:\users\dg\documents\python\pgcli\pgcli\main.py", line 331, in cli …
```
> bugfix: make tables query schema filter match schematas query

- pgcli/main.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_pgexecute.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
This would suggest the names of functions create via `CREATE FUNCTION ...`
It doesn't get metadata from functions defined in the pg_catalog schema, which is where `max`, `count`, `sum`, et al. are defined. There's over 2000 functions there so I thought it made sense to stick with the hardcoded whitelist approach currently used for those.
> Autocomplete custom function names

- pgcli/packages/pgspecial.py
- pgcli/packages/sqlcompletion.py
- tests/test_pgspecial.py
-  Move special-related suggestions out of `suggest_based_on_last_token` and into a new `suggest_special` method
- Special commands don't really obey sql syntax so this makes it easier to work around sqlparse
- Have \d, \dt, and \dv suggest schema and table names
- Add support for \df 
- \df suggests schema and function names
- \dn suggests schema names
> Some small \special improvements

- pgcli/pgexecute.py
- tests/test_pgexecute.py
- tests/utils.py
Replace the default JSON (and JSONB, if defined) type casters with versions that handle the incoming data as strings instead of via json.loads. This fixes #163 and makes JSON render the same way in pgcli as it does in psql. The typecaster uses the current connection's encoding — which defaults to the database encoding — to interpret the incoming data; the implementation should continue to behave correctly if someone ever adds the ability to change the client encoding to pgcli.
I tested this against 9.3 and 9.4 servers (yay Docker!).
Comments welcome. :)
> Interpret incoming JSON as a string instead of via json.loads

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_sqlcompletion.py
short version: fixes a bug where `DROP TABLE schema_name.<TAB>` and `DROP FUNCTION schema_name.<TAB>` would both suggest both tables and functions from schema_name.
Previously, if the current word contained a period, `suggest_type` would parse text to the right of the period as `word_before_cursor`, so that characters to the left of the period were parsed as the final token. Then `suggest_based_on_last_token` would generate suggestions under the generic catch-all `elif token_v.endswith('.')`. This means that, for example, `DROP TABLE schema_name.<TAB>` and `DROP FUNCTION schema_name.<TAB>` would each suggest both tables and functions from schema_name.
This commit PR changes this behavior to include schema qualifications as part of word_before_cursor, so that `suggest_based_on_last_token` …
> Better handle schema qualifications in current word

- pgcli/packages/tabulate.py
- tests/test_pgexecute.py
The failure listed in the issue is rooted in how tabulate handles Decimal objects, which, at bottom, end up being rendered via
>>> format(float(Decimal(10000000)), 'g')
'1e+07'
The 'g' format specifier is parameterized in tabulate, but changing it to '' only fixes some of the cases.
Next, I tried asking psycopg2 to return these values as strings rather than Decimal objects, but this also fails due to tabulate's aggressive coercion logic, which ends up giving you
>>> format(float('10000000'), 'g')
'1e+07'
The best solution is to render Decimal values directly as strings, which will correctly handle the difference between 10000000 and 10000000.0. Here is an example in pgcli
postgres> SELECT * FROM numeric_test ORDER BY a
+---------------+
| a             |
|---------------|
| 1.0 …
> Format Decimal values directly as strings

- pgcli/pgexecute.py
I want to add a easter egg for my friend -- command `\cf` -- her name abbreviation,
but when I type `\cf`, it raises `Database name missing.`,
so I have fixed it.
I think it might be useful in the future.
> Fix the checking to commands '\c' or 'use'

- pgcli/packages/sqlcompletion.py
- tests/test_sqlcompletion.py
> Handle a ',' entered before any completions gracefully

- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_pgexecute.py
Originally, tables and schemas starting with `pg_`, as well as `information_schema` were not stored, under the assumption they would generate too many superfluous suggestions. This broke as soon as someone tried to manually add pg_catalog to the search path. #192 
Now, metadata is stored for all tables and schemas, and pg_catalog is correctly reported as being on the search_path, even though it is so implicitly. In order to prevent extraneous suggestions from `pg_catalog`, suggestions starting with `pg_` are suppressed, unless the user has already typed `pg_`, which seems like a reasonable compromise to me.
> Improve handling of pg_catalog in metadata

- .gitignore
- Vagrantfile
- post-install
- post-remove
* to build deb & rpm simply run
```
version=<se.mv.er> vagrant provision
```
vagrant shell provisioner will run the inline script and generate
a deb and an rpm file in the local directory. This is achieved by
multivm Vagrantfile one for centos and one for debian
* To install the generated deb - run sudo dpkg -i
* /pgcli/pgcli_<se.mv.er>.deb (then sudo apt-get install -f if deps
are missing on a clean debian install)
* To install generated rpm - sudo yum install path-to-rpm
* package will be installed under /usr/share/pgcli
* script pgcli will be a symlink in /usr/local/bin/pgcli ->
/usr/share/pgcli/bin/pgcli (with right shebang line
#!/usr/share/pgcli/bin/python)
> Packaging: first cut of working deb and rpm build

- pgcli/pgcompleter.py
- tests/test_smart_completion_public_schema_only.py
When searching for completions in smart completion mode, a potential
suggestion of a user-specified name (e.g. tables, functions, etc.) is
considered a match if the search text appears anywhere in the
suggestion. Keywords, special commands, and built-in functions still
use startswith matching.
Closes #193
> Completion search text matches user-defined entities anywhere in the name

- pgcli/pgexecute.py
Closes #201. 
@drocco007 Can you please verify this PR? 
The json handler is trying to decode the incoming string into unicode based on the database encoding. But this is only required if we're in Python 2, because in Python 3 psycopg2 already converts the string to unicode. But I want to double check my understanding.
The test case shown in #201 clearly highlights the problem. 
```
pgcli>  select '{"foo":42}'::json;
```
> Register the json handler only for PY2.

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- tests/test_parseutils.py
- tests/test_sqlcompletion.py
Previously, 'SELECT * FROM foo WHERE ' correctly suggested columns, but 'SELECT * FROM foo WHERE bar = 1 AND ' incorrectly suggested keywords. This was due to the fact that sqlparse was grouping the entire where clause into a single Where token.
This seems such a simple fix I feel like I'm missing something! Suggestions on any extra tests here would be appreciated
> fix broken suggestions after compound where clause

- pgcli/pgbuffer.py
- pgcli/pgcompleter.py
- pgcli/pgtoolbar.py
From the “not a problem now but could be later” department, this PR is preventative maintenance to fix some incorrect calls to `super()`. The spelling
```python
super(self.__class__, self)…
```
is a subtle error that unfortunately tends to manifest itself long after the call is written. To see why it's a problem, consider this class hierarchy:
```python
class A(object):
def report(self):
print 'A reporting'
class B(A):
def report(self):
print 'B reporting'
super(self.__class__, self).report()
class C(B):
def report(self):
print 'C reporting'
super(self.__class__, self).report()
C().report()
```
The expected output is
C reporting
B reporting
A reporting
but you actually get a stack overflow. The first `super()` call from `C` to `B` works as expected, but in `B.report()`, when called from …
> Fix incorrect super() calls

- pgcli/packages/pgspecial.py
Small fix to show the actual triggerdef, instead of the position of the triggerdef after "CREATE TRIGGER ".
> Fix for listing triggers on \d special.

- pgcli/main.py
- pgcli/packages/parseutils.py
- pgcli/packages/pgspecial.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_parseutils.py
- tests/test_pgexecute.py
- tests/test_pgspecial.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
1. The following contexts now suggest datatypes:
- `SELECT foo::<TAB>`
- `CREATE TABLE foo (bar <TAB>`
- `CREATE FUNCTION foo (bar <TAB>`
- `ALTER TABLE foo ALTER COLUMN bar TYPE <TAB>`
2. The special command `\dT` is now supported, and suggests types (but not tables)
Datatypes are suggested both from a hardcoded whitelist of builtin postgresql types, as well as user-defined custom types. Furthermore, since postgresql treats a table row as a form of composite type, table names are suggested in addition to data types.
The whitelist I just typed from memory of datatypes I use frequently, and would appreciate feedback on what belongs there. (Or we can just use all of them.) You should be able to use `\dT pg_catalog.*` to list all of the built-in types.
> Suggest datatypes

- pgcli/packages/pgspecial.py
error like "coercing to Unicode: need string or buffer, int found"
> Fix error for (\d <table_name> command) if table has rules

- pgcli/packages/namedqueries.py
- pgcli/packages/pgspecial.py
- pgcli/pgclirc
This is the beginning of a patch for saving named queries in pgcli.  Named queries allow you to save and re-execute a query with a short name.  E.g.
```
; Save a query
\ns simple_query select 1;
; Execute saved query
\n simple_query
; List all saved query names
\n
; List all saved query names and the queries
\n+
; Delete saved query
\nd simple_query
```
There's a couple shortcoming that should probably be addressed before merging this PR:
1. Queries are saved in `~/.pgcli`.  This destroys any formatting and comments in the
config file.   It could be fixed by either saving the queries in a separate file or replacing `ConfigParser` with `ConfigObj` which should preserve the formatting and comments.
2. Autocomplete saved queries after entering `\n` and as you type. 
3. Tests
> Saving named queries

- pgcli/main.py
A simple change to make the timing output more human friendly. 
Before:
```
│       21 │ misago_users         │ 0003_bans_version_tracker │ 2014-11-24 14:26:46.043154-08:00 │
├──────────┼──────────────────────┼───────────────────────────┼──────────────────────────────────┤
│       22 │ misago_users         │ 0004_default_ranks        │ 2014-11-24 14:26:46.210618-08:00 │
├──────────┼──────────────────────┼───────────────────────────┼──────────────────────────────────┤
│       23 │ sessions             │ 0001_initial              │ 2014-11-24 14:26:46.218419-08:00 │
├──────────┼──────────────────────┼───────────────────────────┼──────────────────────────────────┤
│   200045 │ abc                  │ def                       │ 2015-02-12 23:29:52.473905-08:00 │ …
```
> Make timing info human friendly.

- pgcli/pgcompleter.py
- tests/test_fuzzy_completion.py
Reviewer: @drocco007 
This is an implementation of fuzzy completion (or true subsequence matching) for schemas/tables/columns/views. This is not enabled for keywords.
Typing `djms` will match `django_migrations`. It is implemented as follows:
When user types `djms` we create a regex pattern that looks like this `(d.*j.*m.*s)` and try to match against the collection. So `django_migrations` will be a positive match. 
In order to produce the relevant ordering in the suggestion menu, there are two ranking values used. 
1. Length of a matching group. 
2. Position of the first matching character. 
Here's how it is used:
Let's say there are two tables `django_migrations` and `misago_threads_post_mentions`. 
Case 1:
If a user starts to type `djm` it will be converted to `(d.*j.*m)`, which will …
> Implement fuzzy completion using regex.

- pgcli/main.py
- pgcli/pgcompleter.py
Closes #225. 
This adds a new special command called `\#` to refresh completions. 
/cc @darikg This is a testament to the idea of having register hooks for special commands. It was ridiculously easy to add this new command. Thank you for the idea. :)
> Add \# to manually refresh the completions.

- pgcli/pgcompleter.py
Previously the named queries were only matched based on starting characters. This change makes the matching to be fuzzy. 
Reasoning: We do start_only matching for keywords, special commands and datatypes. There is no need to restrict the named query matching to start_only. 
/cc @brettatoms
> Make named query names to the fuzzy matched.

- pgcli/main.py
- pgcli/pgcompleter.py
Database names should not be quoted even if they are keywords or have non-alphabets. 
Before this change database names with unicode characters were quoted. So when you try to change db, it will suggest  
But choosing the database name with the quotes will result in error. 
So quoting database names is not a desired behavior. 
/cc @darikg Can you review and merge?
> Do not escape the database names, since they clash with \c commands.

- pgcli/packages/pgspecial/main.py
- pgcli/pgexecute.py
Reviewer: @darikg 
Simple change to raise a custom exception type when a special command is not found.
Previously it used to raise KeyError, but this is not as explicit as I'd like it to be.
> Create a new error type for special command not found.

- pgcli/config.py
Reviewer: @macobo 
During my refactor of the config.py I had chosen to instantiate an empty ConfigObj() and then merge in the default and the user config files on it. But this meant the ConfigObj() that I created didn't have a filename associated with it. This broke the behavior of NamedQueries when it tried to save the queries to the ~/.pgclirc file. This PR fixes that issue.
/cc @brettatoms
> Assign a filename to the config obj.

- setup.py
Upgrading to the latest version of prompt_toolkit (version: 0.40).
No changes to compatibility with pgcli. I've done some manual testing. 
But I'd appreciate some testing from the @dbcli/pgcli-core team. 
/cc @jonathanslenders
> Upgrade prompt_toolkit to 0.40.

- setup.py
Upgrade to the latest prompt-toolkit.
Windows support should now have been improved significantly. Especially the rendering (the completion menu doesn't leave traces anymore), and handling of unicode input. French characters of latin-1 like ``éôë``, etc.. should work correctly.
Normally, there are no backwards incompatible changes in this release.
@darikg: Please have a look.
Cheers,
Jonathan
> Upgrade to prompt_toolkit==0.42.

- pgcli/main.py
- pgcli/packages/pgspecial/iocommands.py
- pgcli/packages/pgspecial/main.py
- pgcli/packages/pgspecial/tests/conftest.py
- pgcli/pgexecute.py
- tests/test_pgexecute.py
- tests/utils.py
Building on @amjith's last specials refactor, this wraps up a lot of the specials.main file into a PGSpecial class, which makes it possible for multiple PGCli instances to coexist in the same python interpreter without interfering with each other through module level globals in pgspecial. While doing this I was also able to weaken some of the coupling between pgspecial, pgexecute, and pgcli.
As before, special commands that do not manipulate state are defined by the `@special_command` decorator, which stores metadata in the `COMMANDS` variable. During initialization of a new PGSpecial object, a *copy* of `COMMANDS` is stored in the member variable `commands`. Further special method registration is done through the method PGSpecial.register, which of course modifies only the member …
> More specials refactoring

- pgcli/packages/expanded.py
- tests/test_expanded.py
In expanded mode the record separator looks like this `-[ RECORD 26 ]-------------------------`. 
The number of dashes used to be calculated based on the longest value of a column. Now this is made a constant for two reasons. 
1. If a column has a really long value (say a multi-line paragraph). The separator will look ridiculous which  would make the expanded output useless. 
2. It is more performant to use a constant value instead of trying to iterate over the whole set of values just to determine the max length to use. 
Reviewer: @macobo
> Make the horizontal separator in expanded mode a constant length.

- pgcli/pgexecute.py
Fixes #274.
This change will enforce utf8 encoding while connecting to a database instead of using the encoding of the database. This is because all of pgcli depends on using utf8.
Reviewer: @drocco007
> Always use utf8 as the default encoding.

- pgcli/packages/pgspecial/dbcommands.py
The result of doing the command "\d schemaname." on my db was
'NoneType' object has no attribute '__getitem__'
This fix makes the output look a lot more like what you would see with
the same command on psql.
> Fix for None dereference on "\d schemaname." with sequence

- pgcli/main.py
- pgcli/pgcompleter.py
- pgcli/pgstyle.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
See #200.
Looks like this:
It turns out this is almost trivially easy to do. However, it breaks all of our completions tests. So I before I go ahead and update all the tests, I wanted everyone to get a chance to suggest what should or should not go in the metadata. I think a simple category label is almost a waste.
As an experiment, I shuffled some code around so I could put special command help text directly in the completions menu:
Let me know what you think! This branch works fine, despite the failing tests, if you want to try it out.
> [wip/rfc] Put meta info in the completions menu

- pgcli/main.py
- setup.py
Reviewer: @macobo 
Upgrading the minimum required version of click to 4.1. We use the output_via_pager() function in pgcli. When the pager is active (if the output is longer than the screen) if a user presses Ctrl-C it will abort pgcli and cause the terminal to go weird. 
This latest version fixes the issue. 
Relevant PR: https://github.com/mitsuhiko/click/pull/351
> Bump up click version to address #288

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- tests/test_parseutils.py
- tests/test_sqlcompletion.py
@darikg Can you review? 
Bug: Entering `select * from foo f left join bar b,` will crash pgcli. Notice the trailing comma at the end. 
After the merge that should be handled correctly.
> Fix the crashing autocompletion on joins.

- pgcli/key_bindings.py
- pgcli/main.py
- pgcli/pgbuffer.py
- pgcli/pgclirc
- setup.py
- Re-enable the open-in-editor functionality. Pressing 'v' in Vi mode or Control-X Control-E in emacs mode should open the EDITOR when the input can be edited.
- Visualization of completions in multiple columns. (This is off by default, but can be configured.)
edit: as always, test before merging ;)
> Integration with prompt_toolkit==0.44

- tests/test_sqlcompletion.py
@darikg These are the regression tests for the WHERE clause completion from PR #341.
You're right I should have added the tests with the PR. My bad.
> Add tests for where clause with keywords.

- pgcli/packages/pgspecial/iocommands.py
- tests/features/crud_table.feature
- tests/features/environment.py
- tests/features/iocommands.feature
- tests/features/steps/step_definitions.py
The 'read_from_file' method was removed but is still being called in external editor command. This adds it back, plus an integration test to make sure the call to external editor works.
> Added read_from_file back into iospecial.

- pgcli/completion_refresher.py
- pgcli/main.py
- pgcli/packages/ordereddict.py
- pgcli/pgcompleter.py
- pgcli/pgtoolbar.py
- tests/features/iocommands.feature
- tests/features/specials.feature
- tests/features/steps/step_definitions.py
- tests/test_completion_refresher.py
@dbcli/vcli-core @dbcli/pgcli-core 
This is my first attempt at making the auto-completion refresh in a background thread. I tried it on a database with 40,000 tables in them and I can see a noticeable different in the startup time. I could get more granular by spawning a thread for each type of completion (eg: tables, views, columns etc), but that'll require some granular locking on data-structures.
Since we get a tremendous speed boost with just one thread, I'm not motivated to do multiple threads.
Please pitch in and let me know if there are better ways of doing this.
> Perform auto-completion refresh in background.

- pgcli/packages/pgspecial/dbcommands.py
- tests/behave.ini
I realised when using `\d+` on a table, there's a bug in formatting the `Referenced by` section:
Using current implementation it shows:
```
Foreign-key constraints:
...
Referenced by:
TABLE "constraint_name" CONSTRAINT "table_name" FOREIGN KEY ...
Has OIDs: no
```
After fix:
```
Foreign-key constraints:
...
Referenced by:
TABLE "table_name" CONSTRAINT "constraint_name" FOREIGN KEY ...
Has OIDs: no
```
> "Referenced by" formatting fix

- pgcli/main.py
- pgcli/packages/expanded.py
- pgcli/packages/pgspecial/main.py
- pgcli/packages/tabulate.py
Adds support for `\x auto` option.
* I'm not totally sure about returning `rows` from `tabulate` but it was the most straightforward way I could think of to reuse the data from `cur`
* The `get_terminal_width` function has been borrowed from Stack Overflow and is not extensively tested
(works well on GNOME Terminal 3.6.2)
> Issue #315 Add support for \x auto

- pgcli/config.py
- pgcli/main.py
- pgcli/packages/pgspecial/namedqueries.py
- pgcli/pgclirc
This is PR #349 by @inkn to move the config file from ~/.pgclirc to ~/.config/pgcli/config. 
I've added one more commit to this PR which will auto-migrate the config file at launch time and print a message at the top. If there is already a config file under ~/.config/pgcli/config then we won't overwrite it. Pgcli will simply print a message saying the user has to merge their ~/.pgclirc to ~/.config/pgcli/config file. 
I've also added default paths that are compatible with Windows. 
@dbcli/pgcli-core Can you please review this? @darikg I'm interested to know if this works as expected in Windows. My Windows VMs have expired, so I'm still downloading a new Windows VM to test this out. 
/cc @inkn I'm going to close #349 since this PR has all of your original commits.
> Move config file to ~/.config/pgcli

- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_pgexecute.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
Fixes #189. Suggest set-returning functions in the appropriate places.
This enhances the amount of function meta-data stored: the function argument list, the function return type, and boolean flags `is_aggregate`, `is_window`, and `is_set_returning`. This is a little bit overkill, in that all we need for this PR is `is_set_returning`, but I plan on using most of this in the future. In particular, after (if) this PR is accepted, I'll have follow up that suggests column names from set-returning functions used as tables. Ultimately after that I'd like to implement function tooltips/hints.
> Suggest functions as tables

- pgcli/main.py
A continuation of the conversation from https://github.com/dbcli/pgcli/pull/366
A small fix to support showing the `\h` list whilst in expanded layout mode.
> Only show expanded layout if valid list of headers provided

- pgcli/packages/sqlcompletion.py
- tests/test_sqlcompletion.py
Previously, this worked correctly, suggesting columns etc. from `a`
`SELECT * FROM abc a JOIN def d ON a.`
But this suggested only keywords:
`SELECT * FROM abc a JOIN def d ON a.id = d.id AND a.`
> Fix suggestions in compound join clauses

- .travis.yml
- requirements-dev.txt
- tests/features/environment.py
- tests/features/steps/step_definitions.py
- tox.ini
This PR:
* Uses a different method of exiting the cli with pexpect (`.terminate()`)
* Updates a regexp to filter out ANSI escape sequences.
* Pins pexpect to 3.3.
* Adds pgspecial to tox.
Connected to #374.
> Fix tests breaking with pexpect 4.0

- pgcli/filters.py
- pgcli/key_bindings.py
New users get frustrated when they select a SQL command, press `Enter` and the command gets executed. So this PR makes the enter key work like the tab, but only when the completion menu is visible.
> Makes "enter" key function as the "tab" key only when the completion menu is displayed

- pgcli/main.py
- pgcli/pgclirc
- pgcli/pgexecute.py
- tests/test_pgexecute.py
I don't like how errors are handled in pgexecute.run:
1. The default behavior with multiple statements, with errors in intermediate statements, is to continue executing the remaining statements. I'd like to be able to override that behavior to stop immediately on errors. 
2. Handling all exceptions makes it more difficult to reuse pgexecute outside of pgcli -- consumers may want to catch their own exceptions
3. \special commands are run outside the try clause. Because named queries can include arbitrary sql, they should be run like any other query
4. The `except` clause is too narrow. Currently, it catches `psycopg2.ProgrammingError`, which includes syntax errors, but not, for example, division by zero errors. See [here](http://initd.org/psycopg/docs/module.html#exceptions) for the …
> Improve error handling in pgexecute

- pgcli/pgclirc
@darikg Can you review and merge? 
I'd like to set the default to STOP since that is the conservative (aka "sane") option.
> Change the on_error default value to STOP.

- pgcli/main.py
Reviewer: @stuartquin 
Related to #369. 
Check for the headers before using expanded mode when `\x auto` is enabled.
> Check for headers in \x auto mode.

- pgcli/main.py
This is a corner case scenario in the background completion refresh. When a user changes to a new database using `\c` and the completion is happening in the background, we still retain the tables and views from the old database and the completion suggestions show old database entries. 
This PR will address this by resetting the completion data-structure before triggering the completion refresh.
> Reset completions when database is changed.

- tests/test_main.py
Right now our tests fail in tox because of setproctitle.
> Setproctitle should be optional in tests.

- .travis.yml
A new version of codecov (1.6.0) was released to PyPi today and our tests on travis starting failing on python 2.6. The log shows some import error in behave, so I have no idea how pinning the codecov version to 1.5.1 fixes it, but it does.
> Pin codecov version in travis.yml

- pgcli/magic.py
- pgcli/main.py
- pgcli/pgexecute.py
- tests/conftest.py
- tests/test_main.py
- tests/test_pgexecute.py
- tests/utils.py
As discussed in #382. Split the RESUME, STOP, RAISE on_error enum into two separate input arguments: `exception_formatter`, a callable that accepts an Exception and returns a (title, rows, headers, status) tuple as if it were a valid query result, and `on_error_resume`, a boolean. If you want `pgexecute.run` to always raise an exception, simply don't supply an `exception_formatter`.
It occurs to me now that the input arguments `on_error_resume` and `exception_formatter` could be moved to instance variables of `pgexecute` instead being being function arguments but that seems like mostly a matter of taste so I'll leave it open for discussion first.
> Tweak on error options

- pgcli/completion_refresher.py
- pgcli/main.py
- pgcli/packages/prioritization.py
- pgcli/pgcompleter.py
- tests/test_completion_refresher.py
- tests/test_fuzzy_completion.py
- tests/test_prioritization.py
- tests/test_smart_completion_public_schema_only.py
Spinning this off from discussion in #377 since they're (mostly) orthogonal.  I was originally a little skeptical of using any learning algorithm because 
1. It might be annoying to have different suggestions on different installations
2. It might preclude improving the base suggestion engine. Right now sqlcomplete suggests only the very vague `keyword` category when it could take greater advantage of syntactical restrictions. Given `SELECT * F`, `FREEZE` is a pretty silly suggestion because it's just not valid sql.
On the other hand, basing suggestions on syntax requires syntactically valid input, and a simple learning algorithm could be much more reliable in the middle of editing temporarily invalid queries. In the long run, the learning approach could move to estimating second- or …
> [experimental] learn keyword preferences

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_parseutils.py
- tests/test_pgspecial.py
- tests/test_sqlcompletion.py
The main goal here is to make it easier to write regression tests using set-based logic. Before, suggest_type returned lists of dictionaries, whose values were lists. Because mutable data structures aren't hashable, it wasn't possible to create sets of suggestions, and mandated the ugly `sorted_dicts` kludge. Here, I've reworked everything to return tuples instead of lists, and namedtuples instead of dicts. For the most part, I think this leads to more readable code, although admittedly one-element tuples are a bit of an eyesore.
> Use only immutable datatypes for suggestions

- pgcli/packages/pgliterals/pgliterals.json
Reviewer: @stuartquin 
Trivial change to add EXPLAIN keyword to the suggestions. 
This is to address issue #415.
> Add EXPLAIN keyword to the completion list.

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_parseutils.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
Surprisingly, manually entering a double quote, as in `SELECT * FROM "` breaks suggestions. This just allows the suggestion system to ignore it.
> Handle manually entered double-quote gracefully

- pgcli/packages/parseutils.py
- tests/test_parseutils.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
`extract_tables` was stopping as soon as it hit the `ON` keyword in the first join clause
Thanks to @jamiely for reporting this issue
> Fix suggestions in multi-way joins

- pgcli/main.py
- setup.py
This is a small change to add humanized time display in parentheses.
Examples:
```
Time: 0.006s (a moment)
Time: 10.005s (10 seconds)
Time: 120.011s (2 minutes)
```
> Added humanized time display. Connect #396.

- pgcli/pgcompleter.py
- tests/test_smart_completion_public_schema_only.py
As @amjith pointed out in #379 keywords don't sort properly after starting to type an identifier
> Really sort keywords after everything else

- pgcli/pgexecute.py
This is to address #426. 
Reviewer: @stuartquin 
There are many datatypes in Postgres and we have to register each datatype to be treated as unicode. This PR registers the `record` datatype to be treated as unicode. I wonder what other datatypes have to be explicitly registered.
> Register a unicode typecaster for record type.

- pgcli/packages/expanded.py
Reviewer: @stuartquin 
We display the `null` values as `<null>` in the tabular output, this PR makes pgcli do the same for expanded output as well. 
Addresses https://github.com/dbcli/pgcli/issues/450
> Display null values as <null> in expanded output.

- pgcli/main.py
- pgcli/pgclirc
I purpose to set the defaut pager "less -SRXF" in pgclirc config file in order to allow users have more flexibility in pager configuration.
In my case I want to have different pager configuration for pgcli/psql than for the rest of the system or use a pager filtered to colorize some expressions:
`pager= grcat ~/.grc/conf.psql | less -iMSx4FXRe`
> Load default pager and its options on load from config file instead of manipulate environment variable

- pgcli/main.py
Since we added two more parameters to the result tuple, we need to update the error case for execute_from_file() special functions. 
Reviewer: @darikg
> Handle a corner case for execute_from_file.

- pgcli/pgexecute.py
- tests/test_pgexecute.py
Addresses BC date issue by typecasting all `DATE` and `TIMESTAMP` results to string.
> Issue #448 extension for BC dates

- pgcli/pgexecute.py
I have added fallback queries that allow the auto-completion indexing to not exception out with the current version of Amazon Redshift. Only tested to a "works for me" state.
> Add fallback queries so that redshift auto-complete indexing doesn't exception out

- pgcli/pgcompleter.py
- tests/test_fuzzy_completion.py
Suppose we have a bunch of tables start with the name `user`, e.g. `user`, `user_group`, `user_action`, `user_address`, etc. When searching for the text `user`, where the match group length and position are identical for all of these items, the current master of pgcli produces completion results in arbitrary order:
This PR adds a new priority fallback — after the fuzzy match group length, position, and history priority — such that, if the existing ranking fails to produce a total ordering, lexical order is used to break the ties. Here is the previous example with this change in place:
> Use lexical order to break ties when fuzzy matching

- setup.py
`pgcli` seems to work fine after `sqlparse` version bump.
Found three failing tests, but are the same which fail with previous `sqlparse` version, so I think it's ok:
```
Failing scenarios:
features/iocommands.feature:3  edit sql in file with external editor
4 features passed, 1 failed, 0 skipped
7 scenarios passed, 1 failed, 0 skipped
57 steps passed, 1 failed, 3 skipped, 0 undefined
```
It seems all are related to editing commands in an external file:
- red: And we start external editor providing a file name
- blue: And we type sql in the editor                      # None
- blue: And we exit the editor                             # None
- blue: Then we see the sql in prompt                      # None
> Upgrade sqlparse requirement to version 0.1.19

- pgcli/main.py
- setup.py
Changes (see 0.58 .. 0.60.):
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG
I also added a simple example of the continuation prompt. This shows dots in front of every next line, when the input is multiline. Feel free to change this.
> Upgrade to prompt_toolkit 0.60.

- DEVELOP.rst
- pgcli/pgcompleter.py
- tests/test_smart_completion_public_schema_only.py
Fix for #475.
The lexical priority was originally implemented as the `-index` of a match text within the lexically sorted collection in `find_matches`.
The problem is when `get_completions` combines results from multiple `find_matches` calls.
As the `-index` is the priority only within the scope of a single `find_matches` call, we end up with jumbling (especially in the case `SELECT * FROM `) because `get_completions` has only the lexical priority to do tie breaking, so it orders the completions as the first elem from all the get_X_matches, second elem from all get_X_matches, etc.
The new lexical_priority is properly comparable when we're combining multiple `find_matches` calls.
I've also added a test for making sure the `SELECT * FROM ` results are ordered.
It looks like this for me:
> Fix lexical order tiebreaking

- pgcli/pgcompleter.py
- tests/test_fuzzy_completion.py
> Fix auto-completion breaking for table names with caps

- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
Initial prototype of #467 
@amjith feel free to check it out. Looks like this for me:
If you select a directory it will start prompting autocomplete for the next characters you input or for everything if you just press tab.
Currently also handles `..` and `~`. What do you think?
> Add \i path completion

- pgcli/main.py
- tests/test_main.py
As you may know, [RFC-3986][1] allows passing "disallowed" characters as long as these are percent encoded.
Since PGCLI deals with the url parsing, we should expect this to happen, and use the values after they have been decoded.
(includes a simple test for the parsing and decoding)
[1]: https://tools.ietf.org/html/rfc3986#section-2.1
> Unquote URI parts prior to using in connection

- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
Change from filtering out all non-set-returning functions to only filteirng out windowing functions and aggregate functions.
Non-set-returning functions are legal in the FROM clause and can be quite useful.
> Improve filtering of functions for FROM clause

- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
prev_tok is something like '[table name] [table alias] USING' where we expect it to be 'USING', so I just added a quick fix where we check the last word in prev_token instead of the whole string.
> Fix bug where "USING(<cursor>" wasn't detected properly + add test case

- .travis.yml
- pgcli/pgexecute.py
- tests/test_pgexecute.py
A simple use case is when someone uses unicode characters in a RAISE statement.
Example: 
```
DO language plpgsql $$
BEGIN
RAISE NOTICE '有人更改';
END
$$;
```
I've added a test. 
Reviewer: @stuartquin
> Support unicode strings in notices.

- pgcli/packages/parseutils.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
This fixes the issue where pgcli interprets **SELECT * FROM Foo** as referring to the table **Foo**, whereas it actually refers to table **foo**.
> Fix problem where non-lower-case table names would not be recognized

- pgcli/packages/parseutils.py
- tests/test_smart_completion_multiple_schemata.py
My previous fix didn't cover the case 'INSERT INTO Foo(\<cursor\>)', which is now covered.
> Fix another problem where table names would not be recognized when nott in lower case

- pgcli/pgexecute.py
This is trivial enough that I'm going to merge it in myself as soon as the tests pass
> pgexecute.foreignkeys() shouldn't explode in postgresql versions < 9

- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_smart_completion_multiple_schemata.py
1. In 'SELECT * FROM Foo.', Foo was not recognized as foo.
2. In 'SELECT * FROM "Foo"', objects in Foo were not suggested.
> Fix two casing issues with schemas

- pgcli/pgcompleter.py
- tests/test_smart_completion_public_schema_only.py
In the expansion, we got '"Foo".\<col\>' when we should have gotten 'Foo.\<col\>'.
> Fix issue with 'SELECT Foo.*<cursor> FROM Foo'

- pgcli/packages/function_metadata.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_function_metadata.py
- tests/test_pgexecute.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
@darikg, please check that this makes sense. It'd be great if we could get rid of all this rather complicated code!
Getting the parameters from proargnames, proallargtypes and proargmodes instead of from parsing the arg_list string simplifies FunctionMetadata quite a bit.
I also made the ColumnMetadata for table/view columns use the same format for the type (i.e. regtype instead of typname). This means we now get join-condition suggestions for joining tables/views to functions, which didn't work before.
> Use pg_proc.proargmodes &c. instead of parsing arg_list

- pgcli/completion_refresher.py
- pgcli/config.py
- pgcli/main.py
- pgcli/pgclirc
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/test_completion_refresher.py
This is for those of us need/want to use unescaped names in CamelCase or whatever. This means we can use pgcli to edit our functions without having to correct the casing all the time!
This adds support for defining the casing to be used in completions (for unquoted names). The casing is determined by the casing file, which consists of a \n-separated list of names using the preferred casing. This file is initially populated based on usage in SQL and PLPGSQL database functions but can then be modified by the user.
> Custom casing of table/column/function/view names

- pgcli/main.py
Since we split pgspecial off into a separate package, its logging statements weren't being written to the pgcli log file. @j-bennet can you review and merge this?
> Add a pgspecial logging handler

- pgcli/pgexecute.py
@amjith you want to merge this tiny fix?
Running the function in #430, I noticed the warnings were printed in reverse order.
> Fix issue where notices/warnings/... were printed in reverse order

- pgcli/packages/parseutils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_parseutils.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
@darikg  you feel like taking a look at this?
This is based on my previous work on suggesting join conditions, but here instead we suggest the whole join. What we do is simply check all the tables in the statement for FK relationships and then suggest joins based on those. I think this will not only save key presses, but also be rather useful when exploring an unfamiliar (part of a) database.
There's one non-obvious change in this commit (that I can think of): When calling **sqlcompletion.text_before_cursor**, the **text_before_cursor** argument now no longer includes **word_before_cursor**. This is because for 'SELECT * FROM foo JOIN bar<cursor>', we would otherwise consider the table **bar** already included in the statement and thus suggest e.g. 'baz on …
> For 'JOIN <cursor>', suggest 'foo on foo.fooid = bar.fooid'

- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
@darikg I think this one's for you.
**Commit message:**
When self-joining a table with an FK to or from some other table, we got a false FK-join suggestion for that column.
There was also a problem with quoted tables not being quoted in the join condition.
And there were a couple of problems when trying to join a non-existent table or using a non-existent qualifier (`SELECT * FROM Foo JOIN Bar ON Meow.`).
I also rewrote get_join_condition_matches a bit in the process, hopefully making it a bit simpler.
> Fix some join-condition issues

- pgcli/main.py
- pgcli/pgclirc
This ports `less_chatty` config option and `NONE` log level from `mycli` to address issue #518.
Related PR:
https://github.com/dbcli/mycli/pull/268
> Ported less_chatty option from mycli.

- tests/metadata.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
@darikg you mind taking a look at this?
This PR has two parts (plus some cosmetic changes):
1. The first commit just consolidates existing duplicated logic in the two test_smart_completion* files into a new file. 
2. Then there are a six commits that make it so that, for some type of completion (table, column, ...), instead of listing every individual completion we expect to get, we just say what kind of completions to get from the test `metadata` dict. E.g. instead of listing every table in the schema `foo` (say for `SELECT * FROM foo.<cursor>`), we simply say we expect `testdata.tables('foo')`. This means we get to write less test code and that fewer tests will break when we expand the test data.
> Remove duplication from smart completion tests

- README.rst
Click 3 is no more. I'd suggest linking to the root of the Click website and letting it redirect to the current stable version since they seem to be removing pages for the older versions.
> Fix link to Click

- pgcli/packages/sqlcompletion.py
The function signature for `suggest_based_on_last_token` was starting to get pretty unwieldy so I wrapped most of those variables into a standalone class unimaginably named `SqlDocument`. This cleaned up  `suggest_based_on_last_token` a little bit and also formalized a couple of repeated patterns there, specifically schema name extraction and the reduction of `text_before_cursor` to a more simplified version by finding the preceding token.
> Some sqlcompletion refactoring

- pgcli/main.py
- tests/test_main.py
When the database URL contains a port, uri.port is (at least in Python 2.7.6) an integer, not a string, so urlparse.unquote chokes on it.
Fixes issue #536, but is probably worth verifying on Python 3.
> Repair exception thrown on urls with ports

- changelog.rst
I'd like to do this release to fix the crashes caused due to the url parsing and redshift fix. This release also bumps the pgspecial version to 1.5.0 which adds support for `\db` command. 
@dbcli/pgcli-core review please.
> Update changelog for release 1.1.0.

- pgcli/main.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgclirc
- pgcli/pgcompleter.py
- tests/metadata.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
@darikg, you showed some interest in this, so would you like to take a look?
If config.main.generate_aliases is True, for `SELECT * FROM `, we suggest `FooBar FB` and `foo_bar fb` instead of `FooBar` and `foo_bar`, respectively.
To be able to add a test, I had to add support for testing with different settings, which meant I could also add tests for casing.
There are two non-obvious changes that I can think of:
1. The lexical sorting of matches is modified so as to sort spaces and underscores before letters and to sort case-insensitively. This is so that e.g `Foob F` comes before 'FooBar FB' when `foob` is input.
2. We now suggest `some_func()` instead of `some_func` (because suggesting `some_func sf` didn't make any sense).
> Suggest table aliases + add tests for casing

- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
@amjith mind taking a look?
This commit makes it so that given `INSERT INTO foo(<cursor1>) SELECT <cursor2> FROM bar;`, we suggest `bar` columns for `<cursor2>` and `foo` columns for `<cursor1>`. Previous behaviour is sugggesting columns from both tables in both cases.
> Better scoping for tables in insert statements

- pgcli/pgexecute.py
When I tried connecting to Redshift with pgcli v 1.0 I got a `alias timestamptz not supported` error. I made this change to avoid this incompatibility.
> Replace timestamptz alias since AWS Redshift does not support it

- pgcli/main.py
- pgcli/packages/expanded.py
- pgcli/packages/tabulate.py
Allows a configurable string for the null result.
I like to use ⊥ to visually distinguish from normal text, so the config value needs to be decoded to unicode. Such decoding should probably be applied to other formatting options, e.g. the prompt.
Ideally, the output formatting would be themeable to make nulls, and other types, more distinguishable!
> configurable null format

- pgcli/completion_refresher.py
- pgcli/main.py
This option makes it so that the executor and the completer use the same database connection. This is needed for the completer to function when using one-time passwords for connecting to the database.
@darikg wanna have a look?
> Add command-line option --single-connection

- pgcli/main.py
- setup.py
**Note** I don't think the tests will pass until the related https://github.com/dbcli/pgspecial/pull/22 is merged. @amjith what would you normally do in this case?
An implementation of `\watch` from psql.
```
SELECT * FROM titles; \watch 1;
```
If the command can be parsed as a 'watch' command it is executed, then we sleep the specified number of seconds then execute again. Ctrl+C cancels
Any feedback and suggestions on testing welcome
> Issue #544 Implementation of watch command

- pgcli/main.py
- pgcli/pgexecute.py
Hello,
first patch is a bugfix (I'm using python2):
```
$ python -m pgcli.main -d "dbname=rjuju"
[...]
File "/.../pgcli/main.py", line 682, in get_prompt
string = string.replace('\\u', self.pgexecute.user or '(none)')
TypeError: coercing to Unicode: need string or buffer, tuple found
```
Second one is to add more placeholder to the new prompt variable:
* \p for server port
* \i for backend PID
* \# for superuser status (same as the %# placeholder in psql)
That's mostly the placeholder I need for my personal use, so feel free to merge only one or no one of these patch.
PS: I didn't use the same placeholder as psql since existing one were already different (except for \#, didn't find better idea). If the one I choose are badly chosen, feel free to change them.
> More prompt

- pgcli/main.py
Reviewer: @koljonen 
This addresses #575. 
We were inaccurately reporting timing data by aggregating the time stamp.
> Remove cumulative addition of timing data.

- pgcli/main.py
- pgcli/pgbuffer.py
- pgcli/pgclirc
- pgcli/pgtoolbar.py
Basically, having to go to the end of the input to delete the semicolon, then back to wherever you want to insert your newline, and then back to the end to re-add the semicolon before executing your edited query is way too complicated, and I keep getting it wrong, resulting in half-written queries being executed and me getting frustrated. 
My suggested solution is to (1) remove the power of the semicolon to decide what [Enter] does, and (2) make the UI (toolbar) tell the user about [Esc] [Enter].
The reason it's [Esc] [Enter] and not [Alt]-[Enter] in the toolbar is that [Alt]-[Enter] doesn't work by default on Mac OS (it requires the user to change the settings of the terminal app).
So ... does anyone else use multiline mode and have an opinion on this?
> Make semicolon not trigger execution in multiline mode

- pgcli/main.py
- pgcli/packages/tabulate.py
- pgcli/pgclirc
- tests/test_main.py
- tests/test_pgexecute.py
- tests/utils.py
I apologize in advance for possible mistakes, first time trying to take part in open source project.  All decimal columns defined as text field, I change this behavior. Now decimal defined as float. Changed default formatting for float and int. And separate int and text cases.
> master: numbers division for int and float

- DEVELOP.rst
- pgcli/packages/prioritization.py
All behaviors and tests pass, with Python 3.6b2. I did not exercise them on previous versions, but I can surely do it, if needed.
> Fix for issue #595

- .travis.yml
@dbcli/pgcli-core 
I'd like to propose that we remove support for Python 2.6. This PR removes Python 2.6 from travis test runs. 
Please let me know if there are any objections. 
Reasons:
* When Python 2.6 first came out George W. Bush was the president of United States. (Let that sink in).
* The official Python 2.6 support ended in Oct 2013. (Three years ago).
* The real reason is I don't have the time to maintain support for it anymore.
> Remove python 2.6 from travis.

- pgcli/pgcompleter.py
- tests/test_naive_completion.py
Python 3 forbids comparisons between different types: use a tuple
containing a single 0 (zero) as the priority for path matches so that it
can be compared with those generated by the workhorse method find_matches().
> Fix issue #603

- pgcli/main.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgclirc
- pgcli/pgcompleter.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
@darikg Do you have time to look at yet another of my tweaks to the completion engine?
> Support for table-qualifying column suggestions
> 
> ... i.e. suggesting foo.fooid instead of just fooid
> Controlled using a config-file setting:
> **qualify_columns**: always/never/**if_more_than_one_table**.
> 
> To enable the proper sorting of qualified column suggestions, we
> introduce the concept of synonyms for suggestions
> (in `pgcompleter.find_matches`). They way synonyms work is that a
> number of synonyms may be provided for a suggestion sent to
> `find_matches`. If synonyms are provided, sorting is based on how
> well the best synonym matches the input, instead of only comparing
> the input to the suggestion text.
> In this case, the unqualified name acts as a synonym.
> I have a couple …
> Table-qualifying column suggestions

- pgcli/main.py
- pgcli/pgclirc
- pgcli/pgexecute.py
- pgcli/pgtoolbar.py
This adds a red "Failed transaction" text to the toolbar if the the current transaction is doomed, and a green "Transaction" text if we're in a non-doomed transaction. 
I'd especially welcome any improvement on the choice of colours/styling, as I feel it's not quite what I wanted (I'd want the text to "pop" more), and I suspect we'll be stuck with whatever initial choice we make.
> Add transaction status to toolbar

- pgcli/pgcompleter.py
- tests/test_smart_completion_multiple_schemata.py
The basic idea is that we should be able to type a table alias and have it completed to the table name with just one key press. E.g. I type `SELECT * FROM ufg<tab>` and the result is `SELECT * FROM UserFunctionGroups UFG`. I expanded this idea a bit, so that I can type `select gdm<tab>` and get `select get_department_manager()`, or type `SELECT ... ORDER BY ttn<tab>` and get`SELECT ... ORDER BY TransferTypes.TransferTypeName`.
@darikg I added you as a reviewer (not sure how that feature works). It's quite possible that every line of code I touch in this PR is one you've reviewed before in some old PR of mine.
> Search suggestions by initialism

- pgcli/main.py
- pgcli/pgclirc
This makes it possible to enable through the configuration the always
expand and automatic expansion modes in pgcli.
> Per #298, make expand modes configurable.

- pgcli/main.py
Connect #587 : switch the shorted prompt when prompt length is too long (if using the default prompt).
> Switch the shorted prompt when prompt length is too long. 

- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
This is super simple I just wanted `ALTER TABLE foo ALTER ` to suggest `COLUMN`
> Suggest keywords after ALTER

- pgcli/main.py
- pgcli/pgclirc
By default we only reserve 4 lines for the suggestion menu, which feels cramped to me. This just makes the number of lines user-configurable
> User config to reserve more menu space

- pgcli/pgexecute.py
Reviewer: @darikg 
This fixes #646 
Looks like psycopg2 released a new version yesterday that broke us. 😞 
The change was you can't change the `autocommit` status while a cursor is still active. So I moved the sql execution after we set the `autocommit` to `True`.
> Adjust the connection order to work around psycopg2 restriction.

- pgcli/main.py
This addresses #643. 
We should have been reconnecting on all OperationalErrors. 
Docs: http://initd.org/psycopg/docs/module.html#psycopg2.OperationalError
> Reconnect on OperationalError.

- changelog.rst
- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_sqlcompletion.py
Consider this script
```
CREATE FUNCTION foo() returns text LANGUAGE SQL AS $func$
SELECT 1 FROM Bar;
SELECT <cursor> FROM Baz;
$func$;
```
The change here is that `SELECT <cursor> FROM Baz;` will be seen as the
current statement, instead of the whole function definition.
This means we'll no longer get column suggestions from `Bar`.
> Parse function bodies

- pgcli/main.py
- pgcli/pgclirc
- pgcli/pgcompleter.py
- tests/test_smart_completion_multiple_schemata.py
I keep typing e.g. `SELECT mff` and getting annoyed when `someschema.my_fancy_function()` isn't suggested because I forgot to type the schema first. So this fixes that, for tables, views functions and datatypes.
There's a config option for getting the old behaviour.
I added some rudimentary tests. I'm working on another branch where I'll make it more convenient to run the same test for different completer configs, which will add some more test cases for this feature as well.
Sending this to you @darikg, as it's related to a bunch of my other stuff you've reviewed.
> Suggest objects from schemas not in search_path

- pgcli/main.py
This is an attempt to fix #668 .
There's another PR to do the same: https://github.com/dbcli/pgcli/pull/669, but it does not fix the problem completely, because we need to reset the cli buffer in most cases. Editor command seems to be the special case where we don't want the reset.
This PR is work in progress, because I dislike using internal `prompt_toolkit` API like this. I would like very much for @jonathanslenders to weigh in on this.
cc @amjith @jdpopkin
> Attempt to fix #668 (not pretty).

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
Makes the character used for continuing multi-line queries configurable. To me, having a space rather than '.' is cleaner, (particularly when pasting the query/output for others to read). 
Now, setting `multiline_continuation_char = ' '` changes:
```
postgres@localhost:testdb1> SELECT *
........................... FROM foo
........................... WHERE bar = 1;
```
to
```
postgres@localhost:testdb1> SELECT *
FROM foo
WHERE bar = 1;
```
> Allow configurable multiline continuation char

- AUTHORS
- changelog.rst
- pgcli/main.py
This standardizes on the same names as psql and removes some
conflicts.
I was using a database tool that was launching pgcli (thinking it was psql) with the `--username` option. This failed as pgcli expected the username option as `--user`. Since pgcli has extra and different functionality than psql it makes sense to have additional command line options but I think it's important for compatibility purposes to mimic psql's command line interface.
> Standardize command line option names

- README.rst
It took me a little long to find the config options.
Reasons to make it more visible I think are:
* The location is not in the help text
* Not everyone is familiar with the convention of .rc files going in `XDG_CONFIG_HOME`.
* Often options are explained in the readme; I thought it nice to at least mention where one could find a description of them.
On the flipside, the readme becomes a little longer.
This contribution isn't noteworthy of course, so I took the liberty to skip the checklist 😁.
> Make it easier to find config option documentation

- pylintrc
- tests/metadata.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
Instead of having a bunch of hard-coded completer fixtures (with different configs) in tests/test_smart_completion_multiple_schemata.py and tests/test_smart_completion_public_schema_only.py, let's have a completer factory in tests/metadata.py. Also, instead of running a test case for one completer config, let's run it for a bunch of different completer configs. That's the basic idea.
Also, I noticed there was some room for deduplication of the smart_completion code, so I moved a bunch of duplicated code from the test functions into metadata.py. There's no change in function for any commit except the first ("Parametrize ...").
> Parametrize completer in tests + deduplicate test code

- changelog.rst
- pgcli/packages/sqlcompletion.py
- tests/test_sqlcompletion.py
Having typed an alias name in an `ORDER BY` or (`SELECT`) `DISTINCT` clause,
the alias was not taken account of, and the completion simply listed all
columns. This change fixes that, and makes the autocompletion behave the
same as in `SELECT` and `WHERE` clauses.
> Suggest columns for `ORDER BY` and `DISTINCT` (fixes #685)

- changelog.rst
- tests/features/environment.py
- tests/features/steps/basic_commands.py
- tests/features/steps/crud_database.py
- tests/features/steps/iocommands.py
behave quit pgcli nicely so that coverage can be collected, before this patch pgcli was killed by pexpect at the end of a feature test
> behave quit pgcli nicely

- pgcli/packages/parseutils/meta.py
Just noticed that it was "type" instead of "typ" in the list comprehension.
I'm not sure what cases this issue was covering, so sorry, I have no idea what to write in changelog.
It's also too minor to add myself to the `AUTHORS` :)
> Fix typo in parseutils.meta.FunctionMetadata

- changelog.rst
- pgcli/main.py
> User option should take precedence over environment variable.

- changelog.rst
- pgcli/main.py
This addresses #434. It relies on https://github.com/dbcli/pgspecial/pull/33.
If a query has been run in the current session, opening the external editor `\e` will bring the last-run query into the editor. Otherwise, the editor will be blank.
The behavior remains the same for editing a current query (e.g. `select \e`).
> Edit last-run query in external editor.

- AUTHORS
- changelog.rst
- pgcli/main.py
I added a date option for the prompt (as asked for in #580 ). To use it, you just have to add "\\t" to the Prompt Format option.
> Adding time option for the Prompt Format

- AUTHORS
- changelog.rst
- pgcli/completion_refresher.py
- pgcli/main.py
- pgcli/pgexecute.py
- tests/test_completion_refresher.py
- tests/test_main.py
This adds support for additional url query params which make stuff like
```
pgcli "postgres://user:pass@host.invalid/db?\
sslmode=verify-full&sslcert=my.pem&sslkey=my-key.pem&sslrootcert=ca.pem"
```
work. More generally it allows one to pass through various extra connection
options.
> Make it possible to use SSL with pgcli

- README.rst
- changelog.rst
Updates the macOS installation instructions to use dbcli's Homebrew tap.
This address #718.
> Update Homebrew install instructions

- README.rst
Fix some incorrectly formatted links using markdown syntax.
> Use RST style links

- changelog.rst
- pgcli/packages/parseutils/meta.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/metadata.py
- tests/test_pgexecute.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_sqlcompletion.py
When expanding * for `INSERT INTO tbl(*`, skip columns that have a default value of either some sequence (`nextval(...`) or of `now()`.
> Better * expansion for inserts

- release.py
Fixed the release script; `tag -s` command won't work (will get stuck expecting user input) if a message is not provided.
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there)~.
> Signed tags also need a message. Mhm.

- pgcli/pgclirc
User `auto` as the default casing in config file.
~~[ ] I've added this contribution to the `changelog.md`.~~
~~[ ] I've added my name to the `AUTHORS` file (or it's already there).~~
> Change the casing default to 'auto'.

- tests/features/db_utils.py
- tests/features/environment.py
Fixes the problem with behave tests disregarding PGHOST and PGPORT. This is needed if using a dockerized postgres instance for testing.
Example command that did not work before:
`PGHOST=localhost PGUSER=postgres PGPORT=8432 behave`
(note the non-standard port because it's forwarded from the docker container).
> Behave tests should also accept pgport.

- pgcli/main.py
- pgcli/packages/parseutils/utils.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgbuffer.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
This is rather not really an issue as it is, but this changes allow to avoid ambiguity in slashes interpretation in strings (W1401).
> Use raw strings where needed to avoid backslash ambiguity

- changelog.rst
- pgcli/pgexecute.py
Use psycopg2 to get database details when connected.
Fix #765
> Use psycopg2 to get database details

- changelog.rst
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- tests/test_pgspecial.py
- tests/test_smart_completion_public_schema_only.py
E.g. after `\df`, we want to suggest only function names.
@amjith, you feel like merging this?
> Don't include args in function suggestions for backslash commands

- changelog.rst
- pgcli/packages/pgliterals/pgliterals.json
Fix #769
Add missing keyword COLUMN after DROP.
> Add COLUMN as possible keyword after DROP

- changelog.rst
- tests/conftest.py
- tests/utils.py
Fix TODO, optionally use POSTGRES_USER, POSTGRES_HOST POSTGRES_PASSWORD from environment
> Fix TODO, optionally use POSTGRES_USER, POSTGRES_HOST POSTGRES_PASSWORD from environment

- changelog.rst
- pgcli/main.py
- tests/features/steps/expanded.py
- tests/test_main.py
- tests/test_pgexecute.py
Preliminary work for a future change in outputting results that uses less memory
> Preliminary work for a future change in outputting results that uses less memory

- changelog.rst
- pgcli/main.py
use cursor from psycopg in pgcli
I'm not sure if you should/can use hardcoded numbers to match the `type_code` of Cursor.description
> use cursor from psycopg in pgcli

- changelog.rst
- setup.py
Drop wcwidth dependency (this is only used in cli_helpers which is a dependency for pgcli)
> Drop wcwidth dependency

- changelog.rst
- pgcli/main.py
Remove shebang and git execute permission from pgcli/main.py.
pgcli/main.py can't be executed directly because of the package structure.
removal of the shebang is required for packaging in Fedora
> Remove shebang and git execute permission from pgcli/main.py.

- .travis.yml
- changelog.rst
- requirements-dev.txt
- tests/features/environment.py
- tests/features/iocommands.feature
- tests/features/steps/iocommands.py
This is an attempt to fix the `tee` test breaking: https://github.com/dbcli/pgcli/issues/795.
Also, this fixes the error in `notee` test which should not be `notee` (that's a mycli command) but `\o`: https://github.com/dbcli/pgcli/issues/797.
> Fix for tests breaking after tee.

- changelog.rst
- pgcli/pgcompleter.py
Don't quote the database names regardless of the mixed case.
> Do NOT escape database names.

- tests/features/environment.py
This uses Ctrl + C to clean up after test scenario (thanks @meeuw).
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there)~.
> Use ctrl + c instead of ctrl + u to clean up command line after tests.

- changelog.rst
- pgcli/pgexecute.py
An attempt to fix https://github.com/dbcli/pgcli/issues/805. The `unix_socket_directories` setting may not be present in `pg_settings` view. I'm not sure if this will fully fix the problem, as I was not able to completely reproduce the conditions. But the safeguard is needed when retrieving the setting anyway.
> The unix_socket_directories setting may not be present.

- changelog.rst
- tests/features/environment.py
Increase timeout for quitting pgcli
> Increase timeout for quitting pgcli

- pgcli/main.py
As described in ticket #823, this is useful for matching prompt for
different usernames and auto populating passwords. iTerm2 has password
manager that is capable of doing this, but other terminal managers might
be able to do it as well.
`behave`, `pytest` and `pep8radius` are passing locally. I have not tried building `deb` or `rpm` packages, but these changes should not affect that in any way.
I am opened for any feedback you might have.
> Include username to password prompt. #823

- AUTHORS
- pgcli/pgclirc
This PR is to a correct a small typo `DNS` -> `DSN` in a comment in the pgclirc.
> correct typo in pgclirc comment

- .travis.yml
- changelog.rst
- setup.py
- tox.ini
Removed support for Python 3.3 (end-of-life).
> Removed support for Python 3.3.

- DEVELOP.rst
The link to the `pgspecial` points to a 404 page (wrong organization).
No need to add my name for such a small fix in my opinion. Looking forward to contributing more.
> Fix link to pgspecial project

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
This patch makes \h in the prompt only return the hostname up to the first period (i.e. db.orgname.org will be displayed as just 'db'), and adds \H which will return the whole hostname.  If there's no '.' in the hostname, \h and \H will produce identical results.
The `get_prompt()` method doesn't seem to have a test suite that exercises all of the format characters; should it?  I did verify that `get_prompt()` is at least invoked by the behave tests.
> #858: make \h in prompt return the first part of the hostname; add \H to return whole hostname

- changelog.rst
- pgcli/main.py
- tests/features/basic_commands.feature
- tests/features/steps/basic_commands.py
Adding `application_name` to help identify `pgcli` connections to postgres.
Fix #868
> Add application name

- README.rst
- pgcli/main.py
There's already a code comment illustrating how you could use SSL with PostgreSQL. This PR:
- Alters that comment to replace `ssl-cert` ([has an extra dash not found in PostgreSQL 1.0 settings](https://www.postgresql.org/docs/10/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS)) with `sslrootcert` (which could be used to [connect securely to Redshift](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html))
- Documents how to use extra options (adds SSL to the example)
> Encourage users to use SSL

- .github/PULL_REQUEST_TEMPLATE.md
Changelog is `changelog.rst`, not `changelog.md`, this PR edits the GitHub PR template to use the correct filename.
> Switch PR template changelog ext from .md to .rst

- AUTHORS
- changelog.rst
- pgcli/main.py
Enclosed the code to run the text editor in a try/finally, and moved the restoration of saved pre-run callables to the "finally", so that throwing an error won't result in losing the saved callables
> Keep callables

- changelog.rst
- pgcli/main.py
The keyring code seems to fail if you have gnome-keyring installed but aren't running the gnome-keyring-daemon.
Stack trace:
```
2018-05-26 11:22:50,043 (28714/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
File "pgcli/main.py", line 436, in connect
keyring.set_password(\'pgcli\', key, passwd)
File "/lib/python3.6/site-packages/keyring/core.py", line 47, in set_password
_keyring_backend.set_password(service_name, username, password)
File "/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 80, in set_password
collection = self.get_preferred_collection()
File "/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
raise InitError("Failed to unlock the collection!")
keyring.errors.InitError: …
```
> make keyring optional

- pgcli/main.py
This warning gets old.
- ~[ ] I've added this contribution to the `changelog.rst`~.
> Silence psycopg2 warning

- AUTHORS
- changelog.rst
- pgcli/main.py
Hi
Today I've just tried to use `pgcli`. Expected to replace `psql` by `pgcli` command in terminal and connect to PG. I had `--user` option there and pgcli asked me to use `--username`. Probably it would be easy for transitions to use the same option name as well for user.
This change will leave `--username` as it is, and add `--user` as optional argument for compatibility.
> Add --user option like psql has as well.

- pgcli/main.py
Catch the exception thrown when the keyring backend is missing.
I'm not entirely happy with this code. I feel like it is way too nested for my comfort. I welcome a critical eye to the code changes.
> Guard against missing keyring backend.

- AUTHORS
- changelog.rst
- pgcli/pgexecute.py
Instead of whitelisting all errors that do not require reconnecting, we simply
only reconnect if we detect a disconnect has occurred.
psql notably behaves in a similar way: https://git.io/fbxuc#L1461
Fixes #807
1. In one shell:
```
CREATE TABLE hello ( id integer, PRIMARY KEY(id));
BEGIN;
LOCK TABLE hello IN ACCESS EXCLUSIVE MODE;
```
2. In another shell:
```
BEGIN;
LOCK TABLE hello IN ACCESS EXCLUSIVE MODE;
```
3. Hitting Ctrl-C, results in: `^Ccanceling statement due to user request`
4. Hitting a lock timeout:
```
ROLLBACK;
BEGIN;
SET lock_timeout = 3;
LOCK TABLE hello IN ACCESS EXCLUSIVE MODE;
```
similarly results in `canceling statement due to lock timeout`
5. Attempting to perform another statement behaves as expected:
```
postgres@localhost:mytestdb> SELECT count(*) FROM hello; …
```
> Avoid reconnect prompt after error if connection is still valid

- README.rst
That note about tabulate formatting numbers is not relevant anymore.
See https://github.com/dbcli/pgcli/issues/617.
> Reverted docs for 617 now it's fixed.

- AUTHORS
- pgcli/main.py
We run `pgcli` on a headless server, shared by many users.
With the release of 1.10.0 and its new dependency on `keyring`, we noticed that when we tried to connect to our database with username specified via `-U` and password specified via the `PGPASSWORD` environment variable, we would just get this error and then exit:
```
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```
We would really prefer not to have to set up `keyring` per use on headless systems per https://keyring.readthedocs.io/en/latest/?badge=latest#using-keyring-on-headless-linux-systems, since that'd require pulling in way more dependencies.
After we installed `keyring.alt` as the string specified, we were then prompted …
> Fix bug that made `keyring` usage not optional when run headlessly

- changelog.rst
- pgcli/main.py
Fix for this error:
`AttributeError: 'PGCli' object has no attribute 'watch_command'"`
see https://github.com/dbcli/pgcli/issues/909
> Fixes "object has no attribute watch_command"

- .travis.yml
Trying to figure out `AttributeError: _DistInfoDistribution__dep_map` in python 3.4 in travis.
Seems to be fixed by updating either pip or setuptools.
> Update setuptools before install.

- changelog.rst
- pgcli/main.py
Fix for https://github.com/dbcli/pgcli/issues/920.
> Fixes keyring = False not honored.

- tests/conftest.py
- tests/features/environment.py
- tests/features/fixture_utils.py
- tests/features/steps/auto_vertical.py
- tests/features/steps/basic_commands.py
- tests/features/steps/crud_database.py
- tests/features/steps/crud_table.py
- tests/features/steps/expanded.py
- tests/features/steps/iocommands.py
- tests/features/steps/named_queries.py
- tests/features/steps/specials.py
- tests/test_main.py
- tests/test_pgexecute.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
This reverts `absolute_imports` change in tests, because that came with a drawback: `tests` having to be a package, being installed into and polluting `site-packages`. Should we perhaps have `tests` inside `pgcli` package? Challenge for another day.
> Revert abs imports in tests.

- .gitignore
- AUTHORS
- changelog.rst
- pgcli/main.py
- requirements-dev.txt
- tests/features/steps/wrappers.py
- tests/test_main.py
`\pset pager` has three possible values: "always", "on", and "off".
pgcli previously treated all non-"off" values as "always". This change
implements the expected behavior, which is to use the pager when the
output is larger than the terminal height (See \pset pager in
https://www.postgresql.org/docs/9.2/static/app-psql.html). Pgcli adds
to this and also uses the pager when the output is wider than the
terminal width.
Fixes #813
> Respect \pset pager on expected behavior

- changelog.rst
Changelog update to release 2.0.0.
The only change is updating to prompt-toolkit 2.0.
> Changelog update to release 2.0.0.

- changelog.rst
- pgcli/main.py
- tests/features/basic_commands.feature
- tests/features/environment.py
- tests/features/steps/basic_commands.py
- tests/features/steps/iocommands.py
Fix for https://github.com/dbcli/pgcli/issues/951.
> Fix for pgcli --list.

- pgcli/main.py
When there is no port given in a connection URI the sytem should assume the default port 5432.
> Set default port in `connect_uri` when none is given, fixes #958

- pgcli/main.py
I tried to implement the behaviour of the options/arguments `dbname` and `username` to behave exactly as in `psql` with the same precedences.
This should fix #950
Here is a table with the details which I double checked in `pgcli` and `psql` with my changes:
| command | username | database |
| --- | --- | --- |
| `PGDATABASE=foo PGUSER=foo pgcli` | foo | foo |
| `PGDATABASE=foo PGUSER=foo pgcli bar` | bar | foo |
| `PGDATABASE=foo PGUSER=foo pgcli bar bar` | bar | bar |
| `PGDATABASE=foo PGUSER=foo pgcli bar bar -d abc` | bar | abc |
| `PGDATABASE=foo PGUSER=foo pgcli bar bar -U abc` | abc | bar |
| `PGDATABASE=foo PGUSER=foo pgcli bar bar -U abc -d abc` | abc | abc |
| `PGDATABASE=foo PGUSER=foo pgcli bar -U abc` | abc | bar |
| `PGDATABASE=foo PGUSER=foo pgcli bar -d abc` | bar | abc |
| …
> Refactor dbname and username options/arguments to match `psql`-behaviour

- changelog.rst
- pgcli/main.py
In the new version of prompt-toolkit C-Z was not suspending the app. It is now fixed.
> Enable suspend using C-Z.

- AUTHORS
- changelog.rst
- pgcli/main.py
closes #776 
allows users to specify a username by passing a lowercase 'u', as in `pgcli -u username`
> allow passing -u flag (lowercase) to specify username

- pgcli/main.py
This adds a separate timing for query execution. It is useful to see how long things take on database side, and how long on pgcli side (formatting etc.). I am slightly worried that seeing this may make some people unhappy, but on the other hand, it can help us make pgcli better.
> Time execution separately.

- AUTHORS
- changelog.rst
- pgcli/pgexecute.py
Avoid error message on the server side if hstore
extension is not installed in the current database.
Issue: https://github.com/dbcli/pgcli/issues/991
> Determine hstore OID from the system view

- changelog.rst
- tests/features/steps/wrappers.py
All pexpect submodules have been moved into the pexpect package as of version 3.0.
> Use pexpect.TIMEOUT instead of pexpect.exceptions.TIMEOUT

- AUTHORS
- changelog.rst
- pgcli/key_bindings.py
i added the esc key in `pgcli/key_bindings.py` to dismiss the autocomplete. The main reason for this, that it sometimes tends to get in the way of the source, especially if you have multiline selects pasted into pgcli.
since im not that profound into python and its libs you could maybe improve the current solution.
thank you for maintaining this greate piece of software!
> keybinding for dismissing autocompletelist

- AUTHORS
- changelog.rst
- pgcli/completion_refresher.py
- pgcli/main.py
- pgcli/pgexecute.py
Fixes the exception:
```
(pgcli) --- src/pgcli ‹master*M?› » pgcli postgres --single-connection                                                                   1 ↵
/Users/irina/.pyenv/versions/3.7.1/envs/pgcli/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
""")
File "/Users/irina/.pyenv/versions/pgcli/bin/pgcli", line 11, in <module>
load_entry_point('pgcli', 'console_scripts', 'pgcli')()
File "/Users/irina/.pyenv/versions/3.7.1/envs/pgcli/lib/python3.7/site-packages/click/core.py", line 722, in …
```
> Fix crash in get_server_version when using --single-connection.

- pgcli/key_bindings.py
- pgcli/pgclirc
This is a follow up to #928.
Picking 4 spaces whenever a user presses the tab key. Removes the option from the config file.
> Remove the expand_tab option from pgclirc.

- AUTHORS
- changelog.rst
- pgcli/key_bindings.py
#1007, letting `escape` dismiss autocomplete dialogs, had the unintended side effect of disabling the use of `escape` to switch to vi navigation mode. This PR restores that.
> Allow escape to switch to vi navigation mode

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgexecute.py
- tests/test_main.py
We had existing invocations of pgcli like `pgcli postgres://bar@baz.com/?application_name=cow`.
8cd3309b18fc015fc89da3236330f7b35297a998 / https://github.com/dbcli/pgcli/pull/869 broke these with errors like
File "[...]/lib/python2.7/site-packages/pgcli/ main.py", line 466, in connect
application_name='pgcli', **kwargs)
TypeError: type object got multiple values for keyword argument 'application_name'
> Allow application_name to be overridden

- changelog.rst
- pgcli/main.py
Catch the base `KeyringError` vs `KeyringLocked` that does not actually exist in version we require (12.2.0).
Fix for https://github.com/dbcli/pgcli/issues/1040.
> Possibly fix #1040.

- .travis.yml
- changelog.rst
- setup.py
- tox.ini
Python 3.7. Looks like this can only be done with `xenial` and `sudo` in travis right now.
> [WIP] Build pgcli with 3.7.

- AUTHORS
- changelog.rst
- setup.py
This fixes the issue with pgcli not working on Arch Linux, since the package `python2-psycopg2` is already on 2.8.2.
> Allow psycopg2 up to 2.8.2

- AUTHORS
- README.rst
- changelog.rst
Remove the README section which detailed how to force `psycopg2` 2.7 dependency installation from source rather than binary.
`psycopg2` 2.7 would automatically favour installation from binary. A bug affecting some users made it desirable to have the option to install from source instead. The README detailed how to do this using pip's `--no-binary` option (nice!).
`psycopg2` 2.8 has now split the binary and source dependencies into different packages with different names (source: [psycopg2 docs](http://initd.org/psycopg/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8)) which makes the `--no-binary` instructions redundant. To specify source/binary you now need to explicitly specify the desired package.
As of #1060, installing `pgcli` from pip will result in the …
> README.rst: tidy up redundant instructions

- AUTHORS
- changelog.rst
- pgcli/key_bindings.py
Use Alt-Enter to insert a multi-line statement without switching to multi-line mode. Already did it by @amjith [on mycli](https://github.com/dbcli/mycli/pull/748/).
Requested in [#738 of mycli](https://github.com/dbcli/mycli/issues/738).
> Add keybinding for alt-enter to introduce a line break

- changelog.rst
- pgcli/pgbuffer.py
- pgcli/pgexecute.py
- tests/test_pgexecute.py
This feature is copied from mycli to enable temporary expanded mode. 
eg: `SELECT * FROM table_name \G` will show results in expanded mode.
> Add \G as a temporary way to use expanded mode.

- changelog.rst
- pgcli/pgexecute.py
Fixes crash when connecting to PostgreSQL 12 beta 1 (https://github.com/dbcli/pgcli/issues/1058).
Fix based on poking around with `psql -E` (namely `\\d <table name>`).
> Partial fix for #1058.

- AUTHORS
- changelog.rst
- pgcli/magic.py
- pgcli/main.py
- pgcli/pgexecute.py
Changes related to issue #1019.
As advised in the ticket, I added a simple check. After I added this check, I got an error saying the variable `is_special` is undefined so I defined it and set it to `None`.
The output looked like this on my system:
```
sebo@(none):osm_test> ;                                                                                                                                                                                                                      
can't execute an empty query
Time: 0.002s
```
and now it looks like this:
```
sebo@(none):osm_test> ; …
```
> Issue 1019 stacktrace on empty query

- AUTHORS
- changelog.rst
- pgcli/key_bindings.py
Closes https://github.com/dbcli/pgcli/issues/1004
> Add key bindings to consistently move up and down in history

- changelog.rst
- pgcli/magic.py
- pgcli/main.py
- pgcli/pgclirc
- tests/test_rowlimit.py
Opening this PR instead of https://github.com/dbcli/pgcli/pull/1079.
The original PR had some extra commits in it, and I could not find a way to get rid of them.
I added the changes requested in #1018 to show only the `row_limit` amount of rows if there isn't a LIMIT clause in the query. If LIMIT exists, the output is not truncated.
Also, I completely removed the warning message.
I don't know why some tests regarding output fail, I'll check that and try to fix it.
> Issue 1018 display first 1k rows

- .github/PULL_REQUEST_TEMPLATE.md
- changelog.rst
add optional but default squash merge request to PULL_REQUEST_TEMPLATE
> add optional but default squash merge request to PULL_REQUEST_TEMPLATE

- changelog.rst
- pgcli/key_bindings.py
- pgcli/main.py
- pgcli/pgbuffer.py
Use a (conditional) Enter key-binding to force-handle a multi-line
buffer, rather than doing so by (conditionally) disabling the multiline
mode of prompt_toolkit.
This has the benefit of being more efficient (the multiline Condition
filter is called very often, which (due to the repeated query parsing)
causes editing to become slow with a large buffer that ends in a
semicolon), clearer in intent (we want to force-handle the query, rather
than (temporarily) disable multiline mode which indirectly forces the
buffer to be handled) and avoids a bug in multi-line history search
(issue #1031)
> Handle a multi-line query on Enter key-press (fixes #1031)

- changelog.rst
- pgcli/packages/sqlcompletion.py
- tests/test_smart_completion_multiple_schemata.py
- tests/test_smart_completion_public_schema_only.py
- tests/test_sqlcompletion.py
Fixes #1048 so that autocompletion of function arguments takes account of table aliases. 
Now, when given 
```
CREATE TABLE test_table(foo text, bar text);
CREATE TABLE other_test_table(baz integer);
```
When the cursor is at `^` in:
```
SELECT length(tt. FROM test_table tt, other_test_table ott
^
```
the autocomplete options are given as
```
bar column
foo column
```
as expected.
> Take account of table aliases when completing function args (#1048)

- .pre-commit-config.yaml
- pgcli/key_bindings.py
- pgcli/pgbuffer.py
Fix the non-multi line case where the enter key was not recognized when the completion menu was open.
> Fix the condition for <enter> key.

- pgcli/key_bindings.py
Escape then enter intended as two separate key presses is a very common
sequence when using vi mode - returning to normal mode from insert mode
(escape) and then submitting the query (enter). The presence of the
escape-enter key binding overrides this behaviour by inserting
undesirable newlines (newline is be easily inserted when in insert mode
by pressing enter) or by introducing a noticable delay/lag before enter
can be pressed after escape, due to prompt toolkit not being able to
recognise escape immediately (since it may form part of an escape-enter
sequence).
> Disable escape-enter keybinding in vi mode

- setup.py
Get version of module for setup.py in simpler way - just import it.
Unless you are planning to release postfixed versions (like x.y.z-dev) often, there is IMO no need to use regular expressions and ast to determine version number.
In case this is intentional, regular expression alone should be sufficient solution.
> setup: Simplify getting module version

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
support for ansi escape sequences:
my config file:
```
prompt = '\x1b[37m[\h] \x1b[92;1m\u\x1b[36m@\x1b[34m\d\x1b[0m \# '
```
resulting pgcli prompt:
> support ansi escape sequences for prompt colors

- changelog.rst
- pgcli/__main__.py
To execute pgcli as python package, I've added a [`__main__.py`](https://docs.python.org/3/library/__main__.html) file.
> add main file to allow python3 -m pgcli execution

- AUTHORS
- changelog.rst
- pgcli/main.py
Using `is not` for comparing string literals raises warning that != should be
used.
Fixes #1138
> Fix warning raised for using `is not` to compare string literal

- .travis.yml
- README.rst
- changelog.rst
- pgcli/main.py
- pgcli/pgexecute.py
- pyproject.toml
- setup.py
- tests/test_pgexecute.py
- tox.ini
So we can use latest version of prompt-toolit.
Relate: https://github.com/dbcli/pgcli/pull/1149
> Deprecate Python2.7.

- AUTHORS
- changelog.rst
- pgcli/completion_refresher.py
Closing connection explicitly in completion_refresher thread easily fixes https://github.com/dbcli/pgcli/issues/1151
Before fix:
```
postgres=# select datid, datname, pid, application_name, client_addr, state from pg_stat_activity where datname != '';
datid | datname  |  pid  |     application_name     | client_addr | state  
-------+----------+-------+--------------------------+-------------+--------
12707 | postgres |  4092 | psql                     |             | active
19780 | mydb1    | 17843 | pgcli-completion_refresh | ::1         | idle
12707 | postgres | 17825 | pgcli-completion_refresh | ::1         | idle
19780 | mydb1    | 17841 | pgcli-MainThread         | ::1         | idle
(4 rows)
...
postgres=# select datid, datname, pid, application_name, client_addr, state from …
```
> Fix: Unable to drop previously connected-to database

- requirements-dev.txt
This fixes the coverage issue from #1157 , it tunes out that the version of `coverage.py` we are using is broken on Python3.8, which produces some phantom lines. see https://github.com/nedbat/coveragepy/issues/714 (which is actually interesting).
So simply upgrade coverage.py solves the problen.
> upgrade coverage to 5.x

- pgcli-completion.bash
Bash completion script for pgcli.
It allows to <tab> complete database names, users and hosts, plus showing the other available options when calling pgcli from the terminal prompt.
In order to work it steals a couple of functions from psql (postgres CLI client installed by default). 
It is intended to be packaged with the debian package and to be copied on /usr/share/bash-completion/completions/pgcli (filename changes for consistency) upon installation of the package.
Please make the debian package mantainer (Lennart Weller lhw@ring0.de as per `apt-cache show`) aware of it and include it in the relevant section of the installation scripts/package.
I hope it is useful.
> pgcli bash completion script

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
First open source commit! 🍻
This change introduces `show_bottom_toolbar` config option in pgclirc of True or False. Defaulting to True.
This change was requested [here](https://github.com/dbcli/pgcli/issues/939#issuecomment-615469759).
> show_bottom_toolbar - Feature to Show/Hide Toolbar

- pgcli/main.py
fix https://github.com/dbcli/pgcli/issues/1169
> bugfix: don't echo a newline when output is empty.

- setup.py
It has been brought to my attention that without this line pip may try to install packages on environments with python 2. At the moment it does not happen because prompt_toolkit has this constraint, but it's still better to have it explicit.
> add python_requires constraint to setup.py

- changelog.rst
- pgcli/pgclirc
- pgcli/pgstyle.py
- setup.py
New feature!
Support settings for `null`.
close #1185 
(This PR is blocking by the release of https://github.com/dbcli/cli_helpers/pull/61 )
> Support style for missing value.

- AUTHORS
- changelog.rst
- pgcli/pgclirc
- pgcli/pgstyle.py
Since the only way to customize the string, number, keyword color is by changing through `syntax_style = <given_style>`,
I added some custom color types which will overwrite prompt_toolkit's style color via `merge_styles` func.
> Add custom color

- AUTHORS
- changelog.rst
- pgcli/main.py
- setup.py
As per #1015, this removes the `humanize` library in favor of `pendulum` for showing query duration. It does add `dateutil` and `pytzdata` as dependencies, which may not be desirable - just thought I'd throw it out there since it was such an easy change.
> Move from humanize to pendulum library for displaying query duration

- AUTHORS
- changelog.rst
- pgcli/main.py
Today I made a typo in a DSN alias while connecting, and the "invalid DSN" error made me look at my pgcli config file, wondering how it changed, before I realized I just misspelled the alias. So I figured it might be nice to make the error for that case more explicit.
I'm happy to add a test or two but I couldn't find any other tests for the `cli` function / error cases to base it off of.
> More explicit error message when DSN alias is not found

- AUTHORS
- changelog.rst
- pgcli/packages/sqlcompletion.py
Auto completion for schema on functions do not show schema e.g.
`DROP FUNCTION ..` will not show schema.
With this change, the schema is suggested in the same way it is for tables.
> Add schema suggestion for functions

- AUTHORS
- changelog.rst
- pgcli/packages/parseutils/ctes.py
- setup.py
- tests/test_sqlcompletion.py
`sqlparse` `0.4.0` has a breaking change which means that SQL strings which are [only whitespace are no longer parsed as statements any more](https://github.com/andialbrecht/sqlparse/blob/63885dd5f1be3fe519fceb0a21f1f87fdc6aa973/CHANGELOG#L28-L32).
I've run `behave` and `py.test` with Python 3.8.5 on both `sqlparse==0.3.1` and the latest `sqlparse==0.4.1`
Closes #1218
> dependencies: add support for sqlparse 0.4.x

- AUTHORS
- changelog.rst
- pgcli/pgclirc
These config properties got introduced in 41dd24e8 as a means to have
more granular control over the syntax highlighting. The problem is that
these cannot be in the default config file since `get_config()` always
reads both the default config file and the user specified one, and there
is no way to unset these variables in the user specified config file to
restore their default behavior. Even if there would be a way, it
wouldn't be intuitive at all to be required to unset some random
settings under the `[colors]` section just to be able to use the well
documented `syntax_style` setting.
Note that one *can* still set these three lines in their user config
file if they want to utilize them.
Resolves #1212
> Fix issue where `syntax_style` config value would not have any effect

- README.rst
- changelog.rst
- pgcli/main.py
- pgcli/packages/parseutils/__init__.py
- pgcli/packages/prompt_utils.py
- pgcli/pgclirc
- tests/conftest.py
- tests/features/environment.py
- tests/parseutils/test_parseutils.py
- tests/test_prompt_utils.py
This PR adds `UPDATE` queries to the list of queries that we consider "destructive". It also changes `destructive_warning` setting in `pgclirc` from simple boolean to 3 levels:
* all - warn on data-changing queries, including DELETE and UPDATE, schema modifications, or server state commands
* moderate - similar to the above, but only warn on UNCONDITIONAL updates
* off - no warnings
Related to issue https://github.com/dbcli/pgcli/issues/1239.
> Finer control over destructive warning.

- changelog.rst
- pgcli/pgtoolbar.py
After #1208 we stopped crashing for prompt-toolkit versions >= 3.0.6, but started crashing for lower versions. Since we apparently still need version 2, the only workaround I can think of is a runtime check.
> fixed unknown symbol REPLACE_SINGLE in prompt_toolkit < 3.0.6

- changelog.rst
- pgcli/config.py
- pgcli/main.py
- tests/test_config.py
- tests/test_main.py
A [hackernews comment](https://news.ycombinator.com/item?id=26188757) brought up that psql skips the initial comment in `~/.pg_service.conf` even if it doesn't start with `#`, so basically all text before the first section. This PR tries to do the same.
> skip initial comment in pg_session file

- pgcli/config.py
- pgcli/main.py
Fix for https://github.com/dbcli/pgcli/issues/1240. There's a lot of context in the issue already.
The problem is caused by https://github.com/DiffSK/configobj/issues/171. This PR uses a separate instance of ConfigObj, that avoids merges, for writing.
> Preserve comments when writing to config file.

- pgcli/pgtoolbar.py
The previous change did not work on a clean install (`packaging` module is not available, not sure where it comes from). CI passed because we test on an environment with requirements-dev. 
UPD packaging is a requirement for pytest and tox
> fix import

- AUTHORS
- pgcli/main.py
See Issue #1257.
To fix this issue, we needed to have skip_initial_comment consume EOL in the same way no matter the OS.
codecs.open does not provide an option to consider EOLs for each platform in the same way.
[codecs.open is not favored for python 3. ](https://stackoverflow.com/questions/5250744/difference-between-open-and-codecs-open-in-python)
The built-in open does provide for a way to consider EOLs for each platform in the same way.
Therefore, I removed the import of codecs.open and used the standard open feature.
All tests now run on Windows and Linux and the pgcli command appears to work correctly.
> skipping initial comments in pgconfig file did not work on Windows.

- changelog.rst
- pgcli/magic.py
IPython magic doesn't work with [ipython-sql](https://github.com/catherinedevlin/ipython-sql) >= 0.4.0, because they broke the API a little.
> fix IPython magic

- changelog.rst
- pgcli/main.py
Allow other csv pagers besides pspg. Fixes https://github.com/dbcli/pgcli/issues/1238.
> Use configured pager if table format is csv.

- pgcli/pgexecute.py
just a  minor change to make sure SQL comments do not get lost before reaching the backend.
as discussed in https://github.com/dbcli/pgcli/issues/1286
I have run a comparison with psql on a query like
/* TEST123 TAGGING */ select * from /*test 123 */ bizscheme.accounts limit 10;--jkjkjksdds fsdf sdf sd
and postgresql receives comments in the same way now
> no need to strip_comments

- AUTHORS
- pgcli/main.py
- pgcli/pgexecute.py
Added hints about how to port some psycopg2 idioms to psycopg 3. No code was changed.
Feel free to merge this as it is, or you might use it as a base for a psycopg 3 porting branch.
> Add some comments about porting from psycopg 2 to 3

- changelog.rst
- pgcli/main.py
Fix for https://github.com/dbcli/pgcli/issues/1320.
Normally, pgcli simply prints `cursor.statusmessage` that `psycopg2` returns. However, while with other databases `psycopg2` returns `SELECT X`, with Redshift this is just `SELECT`.
This adds missing rowcount in pgcli.
@dvarrazzo This PR does the job, but I wonder if it should be fixed in `psycopg2` instead. What do you think?
> Add rowcount to status returned from redshift.

- changelog.rst
- pgcli/auth.py
- pgcli/main.py
- tests/test_auth.py
Fixes https://github.com/dbcli/pgcli/issues/1338.
The only real change here is catching a more generic `Exception`. Did a small refactor to move the code dealing with keyring into a separate module, to make `main` a bit less verbose.
> Fix exception when getting password from keyring

- DEVELOP.rst
- changelog.rst
- requirements-dev.txt
- setup.py
Some small improvements to make the development cycle better on Windows.
- requirements-dev.txt - ```pexpect``` doesn't work on Windows so I just put in a conditional to skip it on Windows.  Also added ```sshtunnel``` since tests require it.
- setup.py - downloading ```psycopg-binary >= 3.0.14``` on Windows only because Windows won't work without the binary version
- Some additions to DEVELOP.rst to give hints on how to do things on Windows and with VSCode debugging.
> Small developer improvements for Windows-based devs.

- pgcli/pgstyle.py
Updates internal link found in comments.
I tried it and it was dead. https://github.com/jonathanslenders/python-prompt-toolkit redirects to https://github.com/prompt-toolkit/python-prompt-toolkit which has a different structure. This is where that code lives now.
> Fix dead link

- changelog.rst
- pgcli/key_bindings.py
- pgcli/pgbuffer.py
Fixes https://github.com/dbcli/pgcli/issues/1360. Safe multiline mode is not working as expected, there's no way to submit the query.
> Esc + Enter should sumbit the query in safe multiline mode.

- .gitignore
- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/packages/formatter/__init__.py
- pgcli/packages/formatter/sqlformatter.py
- pgcli/pgclirc
- tests/formatter/__init__.py
- tests/formatter/test_sqlformatter.py
New formatter is added to export query result to sql-insert format and sql-update format like mycli:
For example:
```
PostgreSQL postgres@127.0.0.1:5432/test ➜ SELECT * FROM "user";
id  name     email                   phone      description  created_at                     updated_at
--  -------  ----------------------  ---------  -----------  -----------------------------  -----------------------------
1   Jackson  jackson_test@gmail.com  132454789               2022-09-09 19:44:32.712343+08  2022-09-09 19:44:32.712343+08
SELECT 1
Time: 0.028s
PostgreSQL postgres@127.0.0.1:5432/test ➜ \T sql-insert;
Changed table format to sql-insert
Time: 0.001s
PostgreSQL postgres@127.0.0.1:5432/test ➜ SELECT * FROM "user";
INSERT INTO "user" ("id", "name", "email", "phone", "description", …
```
> Feature: Add new formatter to export data to sql like mycli

- AUTHORS
- DEVELOP.rst
- changelog.rst
- pgcli/main.py
- pgcli/packages/parseutils/__init__.py
- pgcli/packages/prompt_utils.py
- pgcli/pgclirc
- tests/parseutils/test_parseutils.py
- tests/test_prompt_utils.py
- tox.ini
* Changed the `destructive_warning` config to be a list of commands that are considered 
destructive. This would allow you to be warned on `create`, `grant`, or `insert` queries.
* Updated the destructive warning message to display the dsn alias if available.
> Changed destructive_warning to take a list of destructive commands

- AUTHORS
- changelog.rst
- pgcli/magic.py
This makes %pgcli work even if you use non-password (e.g. TLS cert) authentication
This change changes `pgcli.magic` to use `PGCli.connect_uri` instead of `PGCli.connect`, to make it work with PG connection urls that use TLS certs for authentication instead of username/password.
I looked into passing the underlying pg connection from sqlalchemy into pgcli instead (it's the `connection` method on `conn.session` to get a dbapi-connection-alike, or `conn.session.connection.dbapi_connection` to get the real underlying connection), but pgcli is using psycopg3 and sqlalchemy is still using psycopg2. So that won't be as easy without writing some sort of compatibility shim (sqlalchemy supports psycopg3 in 2.0, which is still in beta, so this problem will eventually go away)
> magic: use PGCli.connect_uri instead of connect

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
This change:
1. Adds a config option (defaulting to auto-retrying) for whether or not to retry a query after it has failed with an OperationalError.
2. Will only retry at most once on a connection that failed with an OperationalError. This will still be pretty usable and non-invasive in scenarios where we should gracefully reconnect and run a query, as in the scenario outlined in the PR introducing auto-retrying (#1009).
It is not necessarily good to always reconnect and retry queries that fail with an OperationalError. For instance, it might be desirable for a database admin to be able to kill a long-running resource-hogging query that a user left running unattended. Before this change, if the misbehaving query was killed with pg_terminate_backend, it would just be automatically …
> Add config option to not automatically retry connections with operational errors

- .github/workflows/ci.yml
- setup.py
- tox.ini
Add Python 3.11 support, as requested for Fedora in:
https://bugzilla.redhat.com/show_bug.cgi?id=2098775
The tests are failing in Fedora so I guess this PR needs some extra work.
> add python 3.11 support

- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
- tests/features/basic_commands.feature
- tests/features/crud_database.feature
- tests/features/crud_table.feature
- tests/features/expanded.feature
- tests/features/steps/basic_commands.py
- tests/features/steps/crud_table.py
Before this change, cancelling a query with a destructive warning would automatically restart the connection. This can be unintuitive behavior for users that might expect only their destructive warning statement to be cancelled. For instance, a user in the middle of a transaction could have their entire transaction aborted because they cancelled a destructive warning statement, leading to previous non-destructive inserts being lost. 
With the new default for this config option (not automatically restarting the whole connection), the past statements within the transaction will not be lost, and the user may continue executing more statements within the same transaction.
This change adds a config option for whether or not a destructive warning will restart the connection, and defaults it to …
> Do not automatically restart connection on destructive warning

- changelog.rst
- pgcli/pgexecute.py
- tests/test_pgexecute.py
This fixes the issue outlined in #1372 by changing the [psycopg.sql.Identifier](https://www.psycopg.org/psycopg3/docs/api/sql.html#psycopg.sql.Identifier). I would guess this problem originally entered the codebase relatively recently during the port to psycopg3.
Before this PR, `CREATE OR REPLACE VIEW` will not replace the view, and will instead create a new view with the name `<schema>.<view>`, leaving the original view unchanged.
Adds extremely small test assertion to make sure the view is quoted correctly.
> fix psycopg.sql.Identifier in \ev handling

- .github/workflows/ci.yml
- changelog.rst
- pgcli/pgexecute.py
Fix for https://github.com/dbcli/pgcli/issues/1373.
I'm not sure how long this has been broken, possibly since the [port to psycopg 3](https://github.com/dbcli/pgcli/pull/1324). We started using the call to `make_conninfo` vs the old `make_dsn`, but it looks like `make_conninfo` does not expect `dsn=xxx` as part of the parameters.
> Fix connecting with dsn.

- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
Add a config option for always running with a single connection. This is equivalent to always running with the `--single-connection` flag.
This is a very minor change, but this flag seems like it's the type of thing that would be useful to have persist as a regular config setting; for people that use it, it can be annoying to always have to specify it.
Leaving it defaulting to False to have the same behavior as before this change (not specifying the flag will not run in single-connection mode). When the config setting is False, users can still enable it in a non-persistent way by running with the flag in the same way as before.
> Add config option to always run with a single connection

- changelog.rst
- pgcli/pgclirc
Add brief comment detailing the behavior in [pgcli/main.py](https://github.com/dbcli/pgcli/blob/141873f86d299a7c8469392367b820960d01707a/pgcli/main.py#L160).
I also changed the example `pager` setting since it seemed misleading that the `less` options in the `pager` setting would be able to be used as if the `LESS` environment variable is not being set automatically.
> Add comment to pgclirc pager section on default LESS

- changelog.rst
- pgcli/explain_output_formatter.py
- pgcli/main.py
This PR fixes #1393.
In some circumstance `cur` in the `ExplainOutputFormatter.format_output()` method will already have its results fetched and be a `list`.  This PR makes sure all results are loaded by always converting `cur` to be a `list`. This PR won't be meaningfully worse for memory since it's always just a single explain query result.
Also added an `explain_mode` check on a later code path since explain mode query results are already formatted with a `max_width` automatically and we don't need to attempt to convert them to vertical output if they're wider than `max_width`.
> Fix explain output when running with auto-vertical-output or max_width

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
When this option is on, any statement that is deemed destructive (through the use of the existing `destructive_warning` config option) will not be executed unless a transaction has been started. The default value is off (thus not changing the current behaviour).
Demo: [![asciicast](https://asciinema.org/a/564064.svg)](https://asciinema.org/a/564064)
Rationale: I think it's a good practice to execute "destructing" queries within a transaction (even more so when executing multiple queries, obviously!). It provides a last chance to rollback if things go wrong. Especially when it (unfortunately) becomes a reflex to just type "yes, I do want to execute this _destructive_ query, duh!". ;)
Notes:
- tests: I don't know what/which tests to add. I could not see appropriate unit tests to add or …
> feature: Add config option to require a transaction for destructive statements

- pgcli/auth.py
- pgcli/completion_refresher.py
- pgcli/main.py
- pgcli/packages/sqlcompletion.py
- pgcli/pgcompleter.py
- pgcli/pgexecute.py
- tests/features/steps/wrappers.py
- tests/test_main.py
This short pull request removes a few leftovers of Python 2 support. This was prompted by @amjith who detected one such leftover in https://github.com/dbcli/pgcli/pull/1397#discussion_r1140893187.
> Remove leftovers of Python 2 support

- changelog.rst
- pgcli/auth.py
- pgcli/packages/formatter/sqlformatter.py
- tests/formatter/test_sqlformatter.py
Fix sql-insert format emits NULL as 'None' ([issue 1408](https://github.com/dbcli/pgcli/issues/1408)).
> Fix sql-insert format emits NULL as 'None'

- AUTHORS
- changelog.rst
- pgcli/pgtoolbar.py
- setup.py
On Python 3.11 and beyond, `pkg_resources` no longer bundles `packaging`:
```bash
$ python3.11
Python 3.11.4 (main, Jul 25 2023, 17:35:35)
```
```python
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.packaging
File "<stdin>", line 1, in <module>
AttributeError: module 'pkg_resources' has no attribute 'packaging'
>>>
```
That causes this issue in `pgcli`:
```python
File ".../bin/pgcli", line 5, in <module>
from pgcli.main import cli
File ".../lib/python3.11/site-packages/pgcli/main.py", line 52, in <module>
from .pgtoolbar import create_toolbar_tokens_func
File ".../lib/python3.11/site-packages/pgcli/pgtoolbar.py", line 1, in <module>
from pkg_resources …
```
> For Python >= 3.11 directly use packaging to compare package versions

- changelog.rst
- pgcli/main.py
- tests/features/basic_commands.feature
- tests/features/steps/basic_commands.py
If a transaction is ongoing, quitting the cli (with "ctrl-d" or "quit") is not possible anymore. An error message is displayed. The user is forced to commit or rollback the transaction before quitting.
Fixes #1071.
1. I did not add a new configuration option. **This commit thus changes the current behaviour of pgcli** (for good, I believe). This is debatable, I could add a configuration option (off by default) if preferable.
2. I added a "behave" test. This is my first one, feel free to comment if it's not the right way to do it.
3. Demo: [![asciicast](https://asciinema.org/a/571678.svg)](https://asciinema.org/a/571678)
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there).~ (I am already in this file.)
> Refuse to quit cli if a transaction is ongoing.

- .github/workflows/ci.yml
- README.rst
reasons:
- tests passed on PR branches do not mean they will pass on main branch, for e.g. alice changed A in branch-a, bob changed B in branch-b, both tests passed and no conflict, but after merged to main, a bug occurs.
- wanna fix the badge in main branch ;D
> runs test on main branch as well.

- .github/workflows/ci.yml
- README.rst
- changelog.rst
- pgcli/completion_refresher.py
- pyproject.toml
- setup.py
- tests/features/environment.py
- tox.ini
* Drop python 3.7.
* Add python 3.12.
* Other housekeeping.
Blocker:
* https://github.com/sdispater/pendulum/issues/696
> Drop python 3.7, add 3.12

- changelog.rst
- pgcli/pgexecute.py
- tests/test_pgexecute.py
Fixed #1403, improved comment handling when the comment is on the first line.  Also added some more testing for this and simmilar issues as well as rearranged these tests some.
> fixed #1403, improved comment handling

- AUTHORS
- changelog.rst
- pgcli/packages/prompt_utils.py
- tests/features/steps/basic_commands.py
- tests/features/steps/expanded.py
Until now, the destructive query prompt, which is a great feature, uses click `prompt` with `type=bool` to confirm the query, those resulting weird behavior such:
```
postgres@localhost:tests> UPDATE test SET id=0;
You're about to run a destructive command.
Do you want to proceed? (y/n): t
Your call!
UPDATE 0
Time: 0.014s
postgres@localhost:tests>
```
This is because it capture `t`/`true` as yes and `f`/`false` as no, for example
I think we should use click `confirm` which is more suitable for this action
We can use it with default to "No" or without a default and force the user to enter
```
postgres@localhost:tests> UPDATE test SET id=0;
You're about to run a destructive command.
Do you want to proceed? [y/N]: t
Error: invalid input
You're about to run a destructive command.
Do you want …
```
> confirm_destructive_query: Use confirm rather than prompt

- .github/workflows/ci.yml
- changelog.rst
- setup.py
"Unbump" pendulum to released version (3.0.0b1 is a beta version)
requiring 3.0.0b1 gives problems for packing pgcli for Fedora.
> downgrade pendulum to released version

- changelog.rst
Release the pendulum downgrade (https://github.com/dbcli/pgcli/pull/1434).
> Release the pendulum downgrade

- pgcli/pgclirc
See discussion here: https://github.com/dbcli/pgcli.com/pull/59#pullrequestreview-1711756673
The same changes have been (or will soon be) applied on pgcli.com (see https://github.com/dbcli/pgcli.com/pull/60).
> pgclirc: Clarify description of `destructive_warning_restarts_connection` option

- changelog.rst
- pgcli/pgexecute.py
- tests/test_pgexecute.py
When connecting to an IPv4 address (`pgcli -h 127.0.0.1`), trying to
use the "short host" in the prompt (with `\h`) would only display the
first octet (127). Now it shows the full IP.
Fixes #964.
> Fix short host (\h) display in prompt when using an IP address

- AUTHORS
- changelog.rst
- pgcli/main.py
- tests/test_application_name.py
The application_name to be used when connecting to a database can now be specified as a command line argument (--application-name) or be taken directly from environment variables (PGAPPNAME). It still defaults to 'pgcli' when not specified.
Closes #1421.
I added a new click option to support `PGAPPNAME` and created a new class member for `PGCli` which stores the set value. This value is then used during the `connect` method unless a different value was stated in `**kwargs`.
> Support PGAPPNAME

- changelog.rst
- pgcli/pgexecute.py
- tests/features/steps/crud_database.py
- tests/test_pgexecute.py
> Raised notices

- changelog.rst
- setup.py
- tests/features/steps/crud_database.py
> Fix psycopg installation error on windows, Issue #1413

- .github/workflows/ci.yml
- changelog.rst
- pgcli/main.py
- setup.py
- tests/test_main.py
`pgcli` uses Pendulum to display the query execution time in words:
> select pg_sleep(62)
+----------+
| pg_sleep |
|----------|
|          |
+----------+
SELECT 1
Time: 62.066s (1 minute 2 seconds), executed in: 62.063s (1 minute 2 seconds)
Pendulum 3 (which has been released in December 2023 and is now
written in Rust) does not build on 32-bit architectures [1]. As such,
installing `pgcli` on such architectures fails. We could pin Pendulum
to version 2 (which was written in Python and builds "everywhere"),
but requiring a whole library and its own dependencies for such a
small feature seems unwarranted.
This commit thus removes the requirement on Pendulum and replaces it
by a simple "duration-to-words" function.
Fixes #1451.
[1] Upstream issue: …
> feat: Replace pendulum by home-made duration-to-words function

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
- tests/test_main.py
- tests/test_pgexecute.py
To address https://github.com/dbcli/pgcli/discussions/1407, this adds a boolean parameter to the config file called `verbose_errors`. If set, the values of any postgres error fields present (see https://www.postgresql.org/docs/current/protocol-error-fields.html) are appended to the error message.
~(The code that extracts the error fields should be good but I'm not sure if a config parameter is the best place to control this, or whether this PR does everything necessary to introduce a new config parameter.)~ ETA: I've also added the `\v` special command which toggles verbose errors.
> Add verbose_errors config and special command

- changelog.rst
- setup.py
`sqlparse` 0.5.0 was released on 2024-04-13 and contains a security fix for a potential denial of service attack: https://sqlparse.readthedocs.io/en/latest/changes.html#release-0-5-0-apr-13-2024
Other changes mentioned `sqlparse`'s release notes shouldn't break pgcli :crossed_fingers: I've run `pytest` locally (but not `behave`) so will rely on the GH actions to catch any breaking changes.
_[EDIT:] pytest/behave/etc are passing in the GH actions, but seems like there's an unrelated issue with docutils (think maybe `rst2html.py` was renamed to `rst2html`?) but running `rst2html --halt=warning changelog.rst >/dev/null` works locally._
> dependencies: add support for sqlparse 0.5.x

- AUTHORS
- changelog.rst
- pgcli/main.py
- tests/test_main.py
Currently outputting to a file via \o disables the console output, however i often find
myself wanting to both log the results & see them in the terminal too #1424
This patch would add a cli arg `--log-file`, behaving as the same option in `psql`* + a
\log-file special command to enable/disable it from the console
\* https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-OPTION-LOG-FILE
Maybe this is just useful for me and not worth adding but thought i'd submit it anyway,
i'll update changelog, etc later if you decide it's ok to merge
> Add --log-file & \log-file option to always capture output

- AUTHORS
- changelog.rst
- pgcli/main.py
- tests/features/basic_commands.feature
- tests/features/steps/basic_commands.py
This builds in the functionality asked for in #1470; it allows pgcli to replace `pg_isready` from the postgresql command line toolchain
Fixes: #1470
> Add `--ping` as a CLI option

- AUTHORS
- changelog.rst
- pgcli/main.py
`exit` isn't defined as a function or imported in `main.py`, so reaching any code path that attempts to execute `exit(1)` results in a `NameError` being raised:
```
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "[...]/__main__.py", line 415, in <module>
File "[...]/__main__.py", line 399, in run
File "[...]/__main__.py", line 389, in main
File "/usr/lib/python3.10/runpy.py", line 220, in run_module
mod_name, mod_spec, code = _get_module_details(mod_name)
File "/usr/lib/python3.10/runpy.py", line 157, in _get_module_details
code = loader.get_code(mod_name)
File "[...]/__main__.py", line 264, in get_code …
```
> Always exit unsuccessfully with `sys.exit`

- .github/workflows/ci.yml
Integration tests are failing right now. Disabling temporarily.
https://github.com/dbcli/pgcli/actions/runs/13524387415/job/38207720601?pr=1492
```
Scenario: run refresh command             # tests/features/specials.feature:3
When we refresh completions             # tests/features/steps/specials.py:11
And we wait for prompt                  # tests/features/steps/basic_commands.py:70
Then we see completions refresh started # tests/features/steps/specials.py:19
File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/behave/model.py", line 1329, in run
match.run(runner.context)
File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
self.func(context, *args, **kwargs)
File …
```
> Temporarily disable integration tests.

- .gitignore
Adding `tests/behave.ini` to `.gitignore` to lessen the likelihood that somebody commits real db credentials (and also reduces the noise from `git status`)
> Adding behave.ini to .gitignore

- AUTHORS
- changelog.rst
- pgcli/pgcompleter.py
- tests/test_pgcompleter.py
PGCLI advertises the ability to configure a custom `alias_map_file`, enabling users to override table alias generation with predefined aliases of their choosing.
Prior to this change the use of the `alias_map_file` was bugged; the configured file was not used and users would continue to get the auto-generated table aliases.
This change plugs the configured `alias_map_file` into the alias generation process, enabling users to use/see their custom aliases.
> Bugfix alias_map_file not being used for table aliases

- AUTHORS
- changelog.rst
- pgcli-completion.bash
I've added bash completion to services defined in the service file.
It's only triggered after typing `service=`
I've also cleaned some formatting of the file itself to make it consistent
> Add bash completion for services defined in ~/.pg_service.conf

- AUTHORS
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
- pyproject.toml
- tests/test_main.py
Allows per-column formatting for date, time, datetime like columns.
Add a column_date_formats section to your config file with separate lines for each column that you'd like to specify a format using name=format. Use standard Python strftime formatting strings.
More details in https://github.com/dbcli/pgcli/issues/1402
> Adding `column_date_formats` config option

- README.rst
Closes #1502
Installing packages using `sudo pip` is actively discouraged. (This can break some systems. Some distributions actually disable this.) Additionally, I have found that many distributions carry `pgcli`.
* Mention first using distribution packages.
* Recommend the use of `pipx` and `uvx`.
See rendered rst here <https://github.com/alexpdp7/pgcli/tree/main?tab=readme-ov-file#linux>.
> Update Linux installation instructions

- .github/workflows/ci.yml
- changelog.rst
- pgcli/main.py
- pgcli/pgclirc
- pyproject.toml
- tests/features/steps/basic_commands.py
- tests/test_init_commands_simple.py
Implement the init-command feature that is available in mycli.
> Implement init-command similar to mycli.

- .pre-commit-config.yaml
- README.rst
- pgcli/auth.py
- pgcli/completion_refresher.py
- pgcli/key_bindings.py
- pgcli/packages/formatter/sqlformatter.py
- pgcli/packages/parseutils/__init__.py
- pgcli/packages/parseutils/meta.py
- pgcli/packages/parseutils/tables.py
- pgcli/packages/parseutils/utils.py
- pgcli/pgexecute.py
- pgcli/pgstyle.py
- pgcli/pgtoolbar.py
- pgcli/pyev.py
- pyproject.toml
- release.py
- tests/features/steps/basic_commands.py
- tests/features/steps/crud_table.py
- tests/features/steps/iocommands.py
- tests/metadata.py
- tests/parseutils/test_function_metadata.py
- tests/parseutils/test_parseutils.py
- tests/test_application_name.py
- tests/test_auth.py
- tests/test_init_commands_simple.py
- tests/test_naive_completion.py
- tests/test_pgcompleter.py
- tests/test_sqlcompletion.py
- tests/test_ssh_tunnel.py
- tox.ini
Apply `ruff format` to all the things.
Follows https://github.com/dbcli/pgcli/pull/1506.
> Ruff format

- AUTHORS
- changelog.rst
- pgcli/main.py
- tests/test_main.py
I was seeing duration values like `Time: 178.236s (2.0 minutes 58 seconds)`. This change just removes the ".0" off of the "2.0 minutes" by casting hours and minutes to ints.
> Don't include '.0' on minutes and hours for durations when passed as large floats.

- AUTHORS
- changelog.rst
- pgcli/packages/pgliterals/pgliterals.json
- pgcli/packages/sqlcompletion.py
- tests/test_sqlcompletion.py
To be suggested autocompletion when setting the search_path, the keyword's suggestion "search_path TO" will be suggested on a "SET" token, only if the latter is the first token of the SQL statement (to differentiate it from the "UPDATE foo SET"). Then, available schemas are suggested (after the "TO" token).
Resolves #1511
---
I'm open to suggestions if I did anything weirdly.
---
> Add suggestion when setting the search_path
