pgcli/main.py, pgcli/pgexecute.py
Great tool, thanks for developing!
I ran into some trouble getting it to work with a databases containing unicode data and this pull request aims to mend that. See also #24
I also added some extra debugging information to ensure that the proper error message is shown and always logged for ease of debugging.
=> Fix UnicodeDecodeError in python2

pgcli/main.py
Catching specific errors from psycopg2 and using
the pgerror prop instead of message to avoid app
crashing.
=> ISSUE #32 More graceful error management

README.rst
Listed pretty printing as one of features.
=> Update for README.rst features

pgcli/packages/pgspecial.py
=> Fix syntaxerror for special commands like \d+

pgcli/packages/pgspecial.py
Didn't have enough time to do more, but it's a start.
=> made a little bit of the sql prettier

README.rst
See at https://github.com/msabramo/pgcli/blob/patch-5/README.rst
=> README.rst: small tweaks

README.rst, sanity_checks.txt
Some very minor corrections in the README and sanity_checks.txt files
=> Corrected some typos

pgcli/main.py, pgcli/pgexecute.py
=> Support for cancelling queries

pgcli/key_bindings.py, pgcli/main.py, pgcli/pgbuffer.py, pgcli/pgtoolbar.py, setup.py
See #9.
Note that the new version has a slightly different API, which is why this PR is the size it is.
=> Support CTRL+arrow shortcuts, bump prompt_toolkit to 0.26

pgcli/pgexecute.py, tests/test_pgexecute.py
See #93.
Note that if any of the queries raises an error, nothing besides the error is output. This is different behavior from psql which outputs separately for each query:
```
_test_db=# select 1; invalid syntax; select 2;
?column?
----------
1
(1 row)
ERROR:  syntax error at or near "invalid"
LINE 1: invalid syntax;
^
?column?
----------
2
(1 row)
```
Let me know if we want to be fully psql-compatible with this or if this acceptable behavior.
=> Support having multiple queries on the same line.

pgcli/main.py
... when database name is omitted
Fix #101
=> allows pgcli to connect to specified user's database

pgcli/magic.py
=> print sql magic connection alias when using %pgcli magic

DEVELOP.rst, TODO, pgcli/packages/sqlcompletion.py, tests/test_smart_completion.py, tests/test_sqlcompletion.py
Added a section about meta-commands to developer documentation.
ON keyword now suggests tables and aliases on the right side of equal sign also.
=> Documentation and an addition to smart completion for ON keyword.

pgcli/packages/pgspecial.py
=> make \dt and \dv use verbose and pattern arguments

pgcli/packages/pgspecial.py
=> bugfix: \dt query shouldn't restrict schemas if schema qualifer supplied

pgcli/key_bindings.py, pgcli/main.py, pgcli/pgclirc
For https://github.com/amjith/pgcli/issues/136
=> Get vi mode working

pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py, tests/test_sqlcompletion.py
=> Add completion for CREATE WITH TEMPLATE

pgcli/packages/tabulate.py
Thank you for your encouragement.
=> display width character string with wcwidth

pgcli/main.py, pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py, pgcli/pgexecute.py, tests/test_pgexecute.py, tests/test_pgspecial.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py, tests/test_sqlcompletion.py
Had this laying around from a while ago and realized today I never submitted it! Closes #39
=> Suggest view names

pgcli/packages/counter.py, pgcli/packages/parseutils.py, pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py, tests/test_parseutils.py, tests/test_smart_completion_public_schema_only.py, tests/test_sqlcompletion.py
* fix some bugs where `t1 JOIN t2 ...` worked fine but `t1 INNER JOIN t2...` was broken
* support `t1 INNER JOIN t2 USING (` which suggests only columns in common
=> some join-related improvements

pgcli/main.py
=> Add the ability to reconnect.

DEVELOP.rst, README.rst, Vagrantfile, pgcli/main.py, release_procedure.txt
@dbcli/pgcli-core Can one of you review and merge?
=> Update repo references.

pgcli/main.py, pgcli/packages/iospecial.py, pgcli/packages/pgspecial.py, pgcli/pgbuffer.py, pgcli/pgexecute.py, tests/test_pgexecute.py
This PR is a cleanup of #213 to remove extraneous commits added in due to the repo move.
I've cleaned up the commit history. I should have waited to move the repo after merging all pending PRs. That was my bad. 
@j-bennet Doe this look good? 
I'll review the changes and merge it in.
=> Iryna's Editor Command PR

pgcli/key_bindings.py
=> Have Tab autocomplete at cursor

setup.py
Can I get one of you @dbcli/pgcli-core to review and merge?
=> Remove jedi installation hack in setup.py.

pgcli/main.py
=> Remove unnecessary finally clause.

pgcli/main.py
It seems there was a leftover from prompt-toolkit migration.
=> Fix editor mode

changelog.rst, setup.py
I'm prepping for a new release of pgcli. 
I've updated the changelog. Can the @dbcli/pgcli-core team please review the changes?
Leave a :+1: if you're satisfied. Ideally I'd like to do the release by end of tomorrow. But I can also wait longer if you'd like more time. Just let me know. 
BTW, we just merged the 100th PR to pgcli. Kudos to everyone who helped us make this project a success. :tada:  :balloon:
=> Update changelog for 0.17.0 release.

pgcli/config.py
Reduce the complexity of config files. 
Reviewer: @j-bennet
=> Simplify config file handling.

pgcli/key_bindings.py, pgcli/main.py, pgcli/pgtoolbar.py, setup.py
Upgrade to the newest version of prompt_toolkit. This should also fix the issue with slow pasting.
Feel free to make changes to the pull request before merging.
I'm not sure how you are feeling about the circular reference between pgcli_bindings and the main class. It can be a weakref, but it doesn't have to.
=> Upgrade to prompt_toolkit==0.38

pgcli/main.py
=> Added support for PGPASSWORD environment variable. Connect #220.

DEVELOP.rst, behave.ini, features/db_utils.py, features/environment.py, features/fixture_data/help.txt, features/fixture_data/help_commands.txt, features/fixture_utils.py, features/simple_cli_commands.feature, features/steps/step_definitions.py, requirements-dev.txt
=> Started working on integration tests.

changelog.rst
The time has come for the next release. 
Can the @dbcli/pgcli-core team please review the changelog and leave a :+1:? 
I'll merge it in once I get a quorum.
=> Update Changelog for version 0.18.0.

.travis.yml
Link to review coverage:
https://codecov.io/github/dbcli
(login with github).
=> Added test coverage with codecov.io

pgcli/packages/pgspecial/iocommands.py
I'm sort of new to Python so sorry if this isn't great. It appears to work, but I wasn't sure how to get the test db set up so I didn't...run any. Also I sort of hacked the use of the @special_command decorator, but since it seems to work as I expected it, I left it.
I'm new to open source stuff, so I'd be happy to rework and resubmit if you give me any feedback.
=> Add includes '\i' functionality

pgcli/main.py, pgcli/pgclirc
@j-bennet Can you take a look? 
This is just adding a comment in the config file. But this seems to trip up people all the time.
=> Add a comment about the keybindings in pgclirc.

AUTHORS, changelog.rst
We're getting ready to do another release. 
@dbcli/pgcli-core Can you please check the changelog to see if I've missed anything? 
Give it a thumbs up if you're satisfied. I'll merge it in once I get a quorum.
=> Amjith/changelog 0.19.0

changelog.rst
@darikg Can you take a quick look at the change log? I'm going to release this bug fix right away.
=> Update changelog for 0.19.1 release.

pgcli/main.py
This is to address #302. Adds pgclirc location as command line argument or environment variable.
=> Pgclirc file location is being read from command line or env.

pgcli/main.py, pgcli/pgclirc, pgcli/pgstyle.py
@darikg Can you please review? 
This is an attempt at addressing #310. 
It uses `eval()` which is generally frowned upon. But I can't think of a better way to do this. 
Thoughts?
=> Add custom styles for menus, toolbars etc.

pgcli/main.py, pgcli/packages/pgspecial/main.py
@j-bennet Can you review this PR? 
It adds a `\pager` command to special commands. 
This will address #286.
=> Add a \pager special command.

pgcli/main.py, pgcli/pgexecute.py, tests/conftest.py
Using dsn-based approach (no config parsing required).
Connect #289.
=> Added "service" option.

pgcli/main.py, pgcli/packages/pgspecial/iocommands.py
@darikg Can you review? 
This PR enables `\i` to run a file with multiple queries (semi-colon separated) and display the results for each of them. Previously only the results from the last query was displayed.
=> Make \i to run multiple commands and show results.

pgcli/pgexecute.py, tests/test_pgexecute.py
This fixes #335. 
@darikg  Can you review?
=> Multiple queries with syntax errors

pgcli/packages/parseutils.py, pgcli/pgbuffer.py, tests/test_parseutils.py
=> Don't end multi-line query within a quote

pgcli/packages/sqlcompletion.py, tests/features/crud_database.feature, tests/features/crud_table.feature, tests/features/environment.py, tests/features/steps/step_definitions.py, tests/test_sqlcompletion.py
=> Autocompletion in named queries.

pgcli/pgexecute.py, tests/test_pgexecute.py
=> Don't hide functions from pg_catalog

pgcli/main.py, tests/test_main.py
Was only actually checking the first command in multiple commands
=> Fix need_completion_refresh

pgcli/packages/function_metadata.py, pgcli/packages/parseutils.py, pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py, pgcli/pgexecute.py, tests/test_function_metadata.py, tests/test_parseutils.py, tests/test_pgexecute.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py, tests/test_sqlcompletion.py
This is a follow-up to #361. See also discussion in #189.
Here's the upshot:
=> Suggest columns from functions

AUTHORS
@stuartquin Can you review and merge? :)
=> Update AUTHORS to add Stuart to core team.

pgcli/main.py
Fixes #378.
Reviewer: @stuartquin
=> Consolidate the timing information.

pgcli/main.py, setup.py, tests/test_main.py
Hi Guys
First draft at solving https://github.com/dbcli/pgcli/issues/355
Would be good to get some feedback on the approach, particularly the regex's
One thing this doesn't cover is entries in shell history file, will do some research on this.
=> Issue #355 Use setproctitle to hide command line passwords

pgcli/main.py, setup.py, tests/test_main.py
@darikg Can you please check this PR on Windows and merge?
=> Make setproctitle optional in Windows

pgcli/packages/tabulate.py, tests/test_tabulate.py
It's possible I broke something, I don't know the codebase.
=> Fix indentation problems with "explain". Seems to solve #313.

AUTHORS, changelog.rst
We're getting ready to release pgcli 0.20.0. 
I've updated the changelog and AUTHORS file. 
This is a pretty big release. So a thumbs up from @dbcli/pgcli-core would be much appreciated. 
Please let me know if I've missed something.
=> Amjith/release 0.20.0

pgcli/config.py, pgcli/main.py, pgcli/pgclirc, pgcli/pgcompleter.py
@j-bennet @darikg I made a reference implementation of what I had in mind. 
You're welcome to test this and merge or write your own implementation if you're not satisfied. 
I haven't tested this yet, sorry.
=> Switch the location of log/history file based on OS.

pgcli/main.py, tests/test_main.py
This is a fix for #417. 
I've also added some tests to prevent future failure.
=> Fix the bug in auto-expand mode when there are no rows to display.

pgcli/pgexecute.py
=> Concat and return all available notices

pgcli/packages/pgliterals/pgliterals.json
=> Add missing keywords.

pgcli/packages/tabulate.py
I try to encode string  before it is passed to tabulate. It works for my issue.
=> convert enum type to unicode in tabulate. #437

tests/test_pgexecute.py
@j-bennet Can you review and merge?
=> Add a test case for enum unicode case.

pgcli/key_bindings.py, pgcli/main.py, pgcli/pgstyle.py, pgcli/pgtoolbar.py, setup.py
A new pull request with the minimal set of changes required to run on the latest prompt_toolkit.
This doesn't enable new features yet (like mouse support.)
(Not tested on Windows.)
=> Upgrade to prompt-toolkit-0.57

pgcli/main.py, pgcli/pgexecute.py
=> fix execute_from_file after #395

tests/test_main.py
to prevent obvious regressions at least
=> test for recent patch for execute_from_file

setup.py
Addresses #462 
Reviewer: @stuartquin
=> Explicitly add wcwidth as a dependency.

README.rst
Thanks for this great project! :smile: 
Just installed and noticed the config file location in the README was not up to date.
=> Update config file location in README

pgcli/pgexecute.py, tests/test_pgexecute.py
Adds timestamptz to DATE custom extension
=> Issue #448. Add timestamptz to DATE custom extension

setup.py
=> Update pgspecial dependency to 1.3.0

pgcli/main.py
This PR changes adds the encoding to the file that is opened to write the output. 
This is a follow-up to the PR #483
=> Add encoding to the output file.

pgcli/key_bindings.py, pgcli/main.py, setup.py
Changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG
The prompt-toolkit release has been well tested before the release, so I don't expect any issues, but please let me know if this would break something.
=> Upgrade to prompt-toolkit 1.0.0

pgcli/main.py, pgcli/pgexecute.py, tests/features/environment.py, tests/test_expanded.py, tests/test_fuzzy_completion.py, tests/test_main.py, tests/test_parseutils.py, tests/test_smart_completion_public_schema_only.py
I was playing around with [https://www.codacy.com/](Codacy) and found some low-hanging fruit.
=> Remove dead code and fix a broken test

pgcli/pgcompleter.py, tests/test_plan.wiki, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py
I don't know about you guys, but I don't think suggesting * is of use to anyone, and it's in the way for anyone who just wants a column.
=> Stop suggesting * as a column

pgcli/main.py
=> Make pgclirc_file argument optional

pgcli/pgcompleter.py
@darikg suggested I make this a separate PR, so here it is. See #496 for more background.
type_priority is an int that says how to sort these matches compared matches of other types.
type_collection is a an iterable that overrides the internal sorting of the matches.
The use case that motivated this change was to be able to
1) sort join conditions ("t.someid = t2.someid") before table aliases ("t")
2) sort FK-based join conditions before name-based join conditions and integer name-based join conditions before other name-based join conditions.
=> Add priority arguments to find_matches

pgcli/pgexecute.py
=> Filter trigger returning functions from suggestions

pgcli/completion_refresher.py, pgcli/config.py, pgcli/main.py, pgcli/pgclirc, pgcli/pgcompleter.py, pgcli/pgexecute.py, tests/test_completion_refresher.py
Simply store them in that order when getting them from the DB, instead of sorted by name.
=> Order columns by in-table order when expanding *

pgcli/main.py, pgcli/pgclirc, tests/test_rowlimit.py
This should resolve https://github.com/dbcli/pgcli/issues/519
=> Make too many rows warning limit configurable

pgcli/packages/sqlcompletion.py, tests/test_sqlcompletion.py
E.g. so `ALTER TABLE foo ALTER COLUMN ` suggests columns from `foo`. 
@koljonen can you review & merge?
=> `column` keyword suggests columns

setup.py
=> Set pgspecial dependency version to 1.4 or higher.

AUTHORS, changelog.rst
@dbcli/pgcli-core This is a big release. We're going 1.0. 
Please review the changelog and add/edit the entries. 
I'd also like people to take the latest master for a spin and raise any issues you might see. 
I'd like to keep this PR open for a few days before I get input from most of the core team before I do the release. 
Thank you!
=> Update changelog for release 1.0.0.

pgcli/packages/function_metadata.py, pgcli/pgexecute.py
cf #537 
not tested
bugfix: don't call att.atttypid::regtype::text in old versions of postgresql
=> Possible fix for redshift?

setup.py
This is a pending on a pgspecial release (https://github.com/dbcli/pgspecial/pull/21).
=> Upgrade pgspecial to 1.5.0

pgcli/main.py, pgcli/pgclirc
I can also make this configurable if you are keen
=> Show host and user information in prompt

pgcli/packages/parseutils.py, pgcli/packages/sqlcompletion.py, setup.py
The tests pass with python-2.7 and python-3.5, but other than that I didn't do much testing.
=> Upgrade to sqlparse-0.2.0, required for Python-3.5 support

tests/test_pgexecute.py
=> Fix failing tests.

pgcli/pgcompleter.py, tests/test_smart_completion_public_schema_only.py
@amjith  you want to merge this in?
=> Some changes to sorting of suggestions

pgcli/config.py, pgcli/packages/expanded.py
@koljonen Can you review and merge? This is an extension to #556.
=> Read config files using utf-8 encoding.

pgcli/pgcompleter.py, tests/features/named_queries.feature, tests/features/steps/step_definitions.py
And add behave tests.
@amjith you want to merge this?
=> Fix crash bug with named queries

pgcli/packages/sqlcompletion.py, tests/test_sqlcompletion.py
And a regression test.
@amjith, mind merging this in? 
#563
=> Temporary hack for sqlparse crashing after AS

pgcli/pgexecute.py
See psycopg/psycopg2#468 for a minimal example of the problem
=> WIP: Use tweaked version of psycopg2.extras.wait_select to supply a timeout

changelog.rst
@dbcli/pgcli-core Can you please review?
=> Update changelog for version 1.2.0 release.

pgcli/main.py, pgcli/pgclirc, pgcli/pgcompleter.py, tests/test_smart_completion_public_schema_only.py
See #569 
@koljonen want to have a look?
=> Support configuring keyword casing preferences

pgcli/packages/sqlcompletion.py, tests/test_sqlcompletion.py
@amjith , you want to merge this in?
=> Fix crash bug with leading parenthesis

setup.py
Reviewer: @darikg 
Addresses: #585
=> Set sqlparse version dependency to >0.2.0, <0.3.0.

pgcli/packages/tabulate.py
=> Minimal fix for #590

AUTHORS, changelog.rst
@dbcli/pgcli-core Can you please approve?
=> Changelog and authors update for 1.3.0

changelog.rst
Reviewer: @darikg
Can you review and merge? I'll push out a new release as soon as this is merged.
=> Update changelog for version 1.3.1

pgcli/main.py
=> Added --prompt option.

pgcli/packages/parseutils/ctes.py, tests/test_sqlcompletion.py
Anyone feel like merging this tiny fix?
=> Fix crash after `with`

pgcli/pgcompleter.py, tests/test_smart_completion_multiple_schemata.py
We were suggesting all CTE columns regardless of whether the CTE in
question was included in the FROM clause.
This also makes populate_scoped_columns output `TableRefence` namedtuples for CTEs, like it does for tables/views/functions. Previously it would emit strings for CTEs.
=> Fix scoping for columns from CTEs

pgcli/pgclirc
Fixes #629 
Reviewer: @stuartquin
=> Set default data_formatting to nothing.

setup.py
=> Bumped pgspecial to 1.7.0. Connect #627.

README.rst
This does not fix issue #617, but at least documents the behavior.
=> Added documantation about tabulate's number formatting. Connect #617.

.travis.yml, tox.ini
=> Add python 3.5 and 3.6 to test suite.

changelog.rst
@dbcli/pgcli-core Can you please review the changelog and make any necessary edits? 
@j-bennet Can you do a release once this is approved by core team?
=> Changelog update for 1.5.0

pgcli/packages/expanded.py, tests/test_expanded.py
Reviewer: @koljonen 
This fixes #651
=> Add support for unicode chars in expanded mode.

pgcli/main.py
I saw this issue labeled Easy. I took a stab at it and I'm open to feedback.
=> Add a command line option for --less-chatty. Fix #626.

changelog.rst
Let's see if we can track changes as we go.
=> Track recent changes in changelog.

pgcli/pgexecute.py
=> Fix set_session cannot be used inside a transaction when using dsn.

changelog.rst
Bugfix release, mostly just to fix #665.
@amjith Please review.
=> Changelog for bugfix release 1.5.1.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Based on discussion in mycli Google group.
Also see the same in mycli: https://github.com/dbcli/mycli/pull/372
=> PR and issue templates.

.travis.yml, DEVELOP.rst, changelog.rst, requirements-dev.txt
Ported from mycli. Discussion: https://github.com/dbcli/mycli/issues/392.
=> Ported pep8radius addition from mycli.

AUTHORS
Thank you, Amjith. I appreciate it 😄 .
=> Add AlexTes to AUTHORS

setup.py
=> Change author name and email.

AUTHORS, changelog.rst, tests/features/environment.py, tests/features/steps/crud_table.py, tests/features/steps/named_queries.py, tests/features/steps/specials.py, tests/features/steps/wrappers.py, tests/features/wrappager.py
=> behave pager wrapper

pgcli/packages/sqlcompletion.py
This requires https://github.com/dbcli/pgspecial/pull/29, but shouldn't hurt even before it gets integrated.
=> Configure suggestions for \sf

.travis.yml
Travis keeps running scrip steps, even after one of the steps fails (see https://github.com/travis-ci/travis-ci/issues/1066). No need to do that.
=> Fail on first error in travis script.

DEVELOP.rst
`DEVELOP.rst` is wrong since pgspecial has been extracted in a dedicated project. I suggest to simply point to pgspecial project.
=> Update DEVELOP.rst with external pgspecial project

README.rst
I made a mistake in the original README syntax.
- [n/a] I've added this contribution to the `changelog.md`.
=> Fix readme monospace syntax

changelog.rst, tests/features/basic_commands.feature, tests/features/steps/basic_commands.py
=> behave test source command

changelog.rst, tests/features/iocommands.feature, tests/features/steps/iocommands.py
Test using behave the tee command
=> Test using behave the tee command

AUTHORS, changelog.rst, pgcli/pgexecute.py
=> Fix handling of failure to obtain lock

changelog.rst, tests/features/basic_commands.feature, tests/features/crud_database.feature, tests/features/crud_table.feature, tests/features/environment.py, tests/features/iocommands.feature, tests/features/named_queries.feature, tests/features/specials.feature, tests/features/steps/basic_commands.py, tests/features/steps/wrappers.py
Behave remove boiler plate code
=> Behave remove boiler plate code

changelog.rst, tests/features/fixture_data/help_commands.txt
fix pgspecial update in behave tests
=> fix pgspecial update in behave tests

changelog.rst, setup.py
Updated changelog and bumped pgspecial to release pgcli 1.6.0.
=> Preparing to release 1.6.0.

release.py
Addresses https://github.com/dbcli/pgcli/issues/542.
=> Create signed tags in release script.

changelog.rst, pgcli/config.py, pgcli/main.py
=> Fix alias dsn from custom rcfile

MANIFEST.in
As part of creating conda-forge packages for pgcli and pgspecial we should include the license in
the source distribution.
ref: https://github.com/dbcli/pgspecial/pull/38
=> Update manifest to include license in source distribution

changelog.rst, pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py
Fixes https://github.com/dbcli/pgcli/issues/469. Schema name should be quoted in `SET SCHEMA` statement.
=> Schema name should be single-quoted in SET SCHEMA.

changelog.rst, pgcli/main.py
Only set LESS environment variable if it's not already set.
=> Only change LESS in env if not already configured.

pgcli/main.py
Hi,
Standard `NullHandler` is here for a while. It's implementation is even more complete than our own. I suggest to use it.
=> Use standard NullHandler

README.rst
You should to tap the formula repo first
=> Fixed installation instructions via brew

tests/features/expanded.feature, tests/features/steps/expanded.py
End-to-end tests for `\x on, \x off, \x auto`.
=> Added functional tests for expanded mode.

changelog.rst, pgcli/main.py, pgcli/pgexecute.py
Add an option to list databases from command line.
Should fix #206 .
My modifications are open for discussion, I tried my best to fit into existing code, but it may not be perfect.
=> List databases

changelog.rst
Updated the changelog before releasing 1.7.0.
- ~[] I've added this contribution to the `changelog.md`~.
=> Changelog update to release 1.7.0.

changelog.rst, pgcli/key_bindings.py, pgcli/main.py
Fish-style auto-suggestion.
Reviewer: @j-bennet
=> Add fish-style autosuggestion.

README.rst
Update the docs to reflect pgcli moving back to the homebrew-hosted formula.
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there)~.
=> Removed instructions for custom brew tap.

README.rst
I suggest to communicate on test coverage to encourage quality and increase confidence in project.
=> Add coverage badge

README.rst
Fix CodeCov link (was broken)
Add Landscape badge for code quality
=> Fpietka badges

README.rst
This adds an IPython section to the README, to document using pgcli from within IPython console.
=> Documentation for pgcli magic in ipython

changelog.rst, pgcli/main.py, tests/features/auto_vertical.feature, tests/features/steps/auto_vertical.py, tests/features/steps/wrappers.py
Port auto_vertical feature test from mycli to pgcli
=> Port auto_vertical feature test from mycli to pgcli

changelog.rst, setup.py
Require cli_helpers 0.2.3 (fix #513)
=> Require cli_helpers 0.2.3 (fix #513)

changelog.rst
Changelog update for a bugfix release 1.8.1.
- ~[ ] I've added my name to the `AUTHORS` file (or it's already there)~.
=> Changelog update to release 1.8.1.

AUTHORS, changelog.rst, pgcli/config.py, tests/conftest.py, tests/features/environment.py, tests/test_rowlimit.py
Use temporary directory as config directory.
=> Use termporary config in tests

README.rst
Pretty self explanatory. Wouldn't say this requires a mention in `changelog.md` or credit in `AUTHORS`.
=> Adds install command for Debian

setup.py
Bump pgspecial so it's updated with the next pgcli release.
=> Bump pgspecial to 1.9.0.

setup.py, tests/test_main.py
There was a bugfix in cli_helpers (https://github.com/dbcli/cli_helpers/pull/32).
=> cli_helpers bump (fixes a python 2.7 bug).

changelog.rst, setup.py
Changelog update before releasing 1.8.2.
=> Changelog update to release 1.8.2.

AUTHORS, changelog.rst, pgcli/main.py, pgcli/pgclirc
It's related to other PR: https://github.com/dbcli/pgcli/pull/815
And it's a result of discussion with @j-bennet (https://github.com/dbcli/pgcli/pull/815#issuecomment-349180420)
=> Use other prompt (prompt_dsn) when connecting using --dsn parameter (attempt 2)

AUTHORS, changelog.rst
I waited on https://github.com/dbcli/pgcli/pull/820 to release 1.8.2 - now that (and one more change is in).
=> More changes added to 1.8.2 release.

changelog.rst
=> Changed my name in changelog.

pgcli/main.py
Small improvements for pgcli options:
* make sure port number is an int
* make sure pgclirc is a file name
=> Add a couple missing click option types.

changelog.rst, setup.py
Changelog update and pgspecial bump to release 1.9.0.
=> Changelog update, and bump pgspecial for the release.

MANIFEST.in, changelog.rst
Add tests, AUTHORS and changelog.rst to release.
=> Add tests, AUTHORS and changelog.rst to release.

release.py, requirements-dev.txt
I honestly stole all @tsroten's release script tweaks.
=> Ported release script improvements from mycli.

changelog.rst, pgcli/main.py
=> Fix broken pgcli --list command line option

DEVELOP.rst
I wanted to run the behave tests, and had to go read `environment.py` to figure out what needed to go in the .ini file.  This patch gives an example in DEVELOP.rst.
(removing the checklist, as this is a minor change)
=> Give example behave.ini

changelog.rst, tests/test_main.py
Mark tests requiring a running database server as dbtest
=> Mark tests requiring a running database server as dbtest

AUTHORS, changelog.rst, pgcli/main.py
Moves quit command to pgspecial.  This allows completion to work.
=> Add quit commands to completion

changelog.rst, pgcli/packages/sqlcompletion.py, pgcli/pgcompleter.py
Adds completion for table formats with \T.
=> Add completion for table formats

changelog.rst, pgcli/pgexecute.py
=> Restrict the offer to reconnect.

.travis.yml, pgcli/main.py, requirements-dev.txt, setup.py
This PR adds support for remembering prompted passwords using [`keyring`](https://github.com/jaraco/keyring).
TODO:
- Via config file so it doesn't need to be specified each time it's invoked (document in README), CLI option/env var documents nicely but is cumbersome to specify on each usage
=> Remember prompted passwords using keyring

AUTHORS, changelog.rst, pgcli/main.py, pgcli/packages/parseutils/__init__.py, pgcli/packages/prompt_utils.py, pgcli/pgclirc, tests/test_prompt_utils.py
* Modified main.py to confirm with the user if they want to run a destructive warning. This includes adding logic to the click config for destructive config
- [X ] I've added this contribution to the `changelog.rst`.
- [X ] I've added my name to the `AUTHORS` file (or it's already there).
=> Porting in Destructive Warning

changelog.rst, tests/features/crud_database.feature, tests/features/crud_table.feature, tests/features/expanded.feature, tests/features/steps/basic_commands.py, tests/features/steps/crud_database.py, tests/features/steps/crud_table.py
refactor destructive warning in behave tests
=> Refactor destructive warning in behave tests

setup.py
Bump the version of pgspecial to 1.11.0
=> Bump the version of pgspecial to 1.11.0

changelog.rst, pgcli/magic.py
=> Fix for ipython sql connection. Fixes #891.

pgcli/main.py
=> Catch the ^D keybinding using EOFError exception.

MANIFEST.in, changelog.rst, setup.py
Changelog and some cleanup for 1.10.0.
=> Changes to release 1.10.0

changelog.rst
A couple of bugfixes. Keyring problem is the annoying one, so we better fix that.
=> Bugfix release.

pgcli/main.py, pgcli/pgexecute.py
Print server version, unless we're being "less chatty".
=> Print server version as part of welcome message.

changelog.rst, pgcli/main.py, pgcli/pgclirc, setup.py
=> make keyring optional

changelog.rst
Changelog for the bugfix release 1.10.2.
=> Changelog update to release 1.10.2.

setup.py
Update pgspecial req to the latest.
=> Bump pgspecial

changelog.rst
Changelog update for the next bugfix release.
=> Let's release more bugfixes.

.travis.yml, tests/conftest.py, tests/features/environment.py, tests/features/fixture_utils.py, tests/features/steps/auto_vertical.py, tests/features/steps/basic_commands.py, tests/features/steps/crud_database.py, tests/features/steps/crud_table.py, tests/features/steps/expanded.py, tests/features/steps/iocommands.py, tests/features/steps/named_queries.py, tests/features/steps/specials.py, tests/features/steps/wrappers.py, tests/test_main.py, tests/test_pgexecute.py, tests/test_prompt_utils.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py
Fixing tests that failed in https://github.com/dbcli/pgcli/pull/871.
=> Attempt to fix failing tests

changelog.rst, tests/features/steps/wrappers.py
Clean up and add behave logging
=> Clean up and add behave logging

AUTHORS, changelog.rst
Missed changelog update in https://github.com/dbcli/pgcli/pull/959
=> Missed changelog update.

DEVELOP.rst, changelog.rst
clarified a few things in the development docs and added a section to troubleshoot running the tests
=> Contrib guide improv

changelog.rst, pgcli/packages/parseutils/tables.py
=> Fix the StopIteration issue in Python 3.7

changelog.rst
Bugfix release coming up, updating changelog.
=> going to release.

changelog.rst, tests/metadata.py, tests/test_naive_completion.py, tests/test_smart_completion_public_schema_only.py
Added tests for special command completion.
Requires the latest changes from pgspecial master.
=> Fix special commands

setup.py
=> bump pgspecial req.

pgcli/main.py
Fix for the lag problem in v2, part 1 (https://github.com/dbcli/pgcli/issues/979).
~- [ ] I've added this contribution to the `changelog.rst`.~
=> Wrap pgcli completer into ThreadedCompleter.

changelog.rst, pgcli/main.py, pgcli/packages/parseutils/meta.py, pgcli/pgcompleter.py, pgcli/pgexecute.py, tests/parseutils/test_function_metadata.py, tests/test_pgexecute.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py
Fix for the lag problem in v2 (https://github.com/dbcli/pgcli/issues/979).
=> Remove some functions completions

tests/features/environment.py
Also revert unfinished logging change from #956
=> VISUAL overrides the value of EDITOR for the \e command

changelog.rst, tests/features/steps/wrappers.py
Missed logfile for earlier clean up and add behave logging changes. Thanks for finding this @saper!
=> Missed logfile for earlier clean up and add behave logging changes

changelog.rst, tests/test_naive_completion.py, tests/test_smart_completion_multiple_schemata.py, tests/test_smart_completion_public_schema_only.py, tests/utils.py
=> fix unhashable formatted text

AUTHORS, changelog.rst, pgcli/main.py, pgcli/pgclirc
Adding the enhancement requested in #989 to automatically reconnect to the database when the server closes the connection.
I couldn't figure out how to add testing for this since I couldn't find a way to force a disconnect to trigger the auto reconnection.
=> Add reconnect automatically enhancement

changelog.rst, pgcli/pgexecute.py
=> Catch and ignore the system interrupt.

changelog.rst, pgcli/pgexecute.py, tests/test_pgexecute.py
Fixes https://github.com/dbcli/pgcli/issues/1014.
=> Fix for https://github.com/dbcli/pgcli/issues/1014.

changelog.rst, pgcli/main.py
Ask for password in case provided password failed.
Fixes https://github.com/dbcli/pgcli/issues/1020.
=> Ask for password in case of incorrect password.

changelog.rst, pgcli/pgexecute.py
Fix for https://github.com/dbcli/pgcli/issues/1043.
=> More intelligent dsn format

AUTHORS, changelog.rst, pgcli/main.py
Load keyring only when keyring is enabled in the config file.
fix issue: https://github.com/dbcli/pgcli/issues/1041
=> lazy load keyring.

changelog.rst, pgcli/main.py, pgcli/pgexecute.py
=>  Fix usage of pgservice #1035 

changelog.rst, pgcli/pgexecute.py
Fixes https://github.com/dbcli/pgcli/issues/1053.
=> Dsn parameters not always present.

pgcli/main.py, pgcli/pgexecute.py, tests/features/basic_commands.feature, tests/features/environment.py, tests/features/fixture_data/mock_pg_service.conf, tests/features/specials.feature, tests/features/steps/basic_commands.py, tests/features/steps/crud_database.py, tests/features/steps/wrappers.py
Fixed the issue with spaces in password.
Started writing some behavioral tests for some of the command line args. Haven't figured out how to pass in a DSN yet.
=> Handle password spaces

changelog.rst
Update changelog before a new release.
=> Changelog update before release.

pgcli/main.py
Remove reference to dead Google Group from pgcli app.
Change is trivial enough that I'm skipping these:
=> rm Google Group from main.py

tests/features/basic_commands.feature, tests/features/steps/basic_commands.py
Add a behave test to verify error condition.
=> Add a test to verify error message.

AUTHORS, pgcli/magic.py, pgcli/main.py, release.py, tests/features/db_utils.py, tests/features/environment.py, tests/features/fixture_utils.py, tests/features/wrappager.py
Fix logger strings formatting to use lazy string interpolation on few logger calls.
=> Logging cleanup

pgcli/packages/parseutils/utils.py
=> Fix simple typo: thows -> throws

AUTHORS, DEVELOP.rst, changelog.rst
Fixed dead link of behave package in development guide.
=> Fix dead link of behave package.

.travis.yml, changelog.rst, requirements-dev.txt, setup.py, tox.ini
https://www.python.org/downloads/release/python-340/
related: #1139
=> Drop Python 3.4 support

AUTHORS, changelog.rst, pgcli/pgexecute.py
added support for partitioned tables, added relkind "p"
=> Add Support for partitioned tables.

.travis.yml, changelog.rst, pgcli/pgexecute.py, pyproject.toml, setup.py, tox.ini
=> Drop Python3.5.

.travis.yml, changelog.rst, setup.py, tox.ini
=> python3.8: add travis test and setup.py class.

pgcli/pgclirc
Add an example of how to use the colored prompt.
=> Add an example for how to use the colored prompt.

README.rst
Additionally, refer to environment variables which can be used to configure login options.
=> Add --help output to README

AUTHORS, changelog.rst, pgcli/main.py
=> Add support for using pspg as the pager.

pgcli/main.py
Fix for this:
https://github.com/dbcli/pgcli/commit/bcb0c8bce776a5eba9f5425c57c2ec8385f10e94#r38893627
=> Fix bug introduced in #1102.

AUTHORS, Dockerfile, changelog.rst
Running `docker build -t .` command fails with an error:
```bash
Sending build context to Docker daemon  30.38MB
Step 1/4 : FROM python:2.7
---> 68e7be49c28c
Step 2/4 : COPY . /app
---> 519757388c77
Step 3/4 : RUN cd /app && pip install -e .
---> Running in 5f82116c8653
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///app
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build …
```
=> Update python version from 2.7 to 3.8 in Dockerfile

AUTHORS, changelog.rst, pgcli/pgclirc
* Corrected a couple of minor typos in `pgclirc`
* Added name to AUTHORS and noted change in `changelog.rst`
=> Minor typo fixes in pgclirc

changelog.rst, pgcli/packages/parseutils/__init__.py, pgcli/pgexecute.py
Fixes https://github.com/dbcli/pgcli/issues/1193.
=> J bennet/fix sql comment

pgcli/pgstyle.py
Same thing as in mycli - https://github.com/dbcli/mycli/pull/680
=> Add Token.Prompt/Continuation

.travis.yml, pgcli/main.py, pgcli/packages/parseutils/ctes.py, pgcli/packages/parseutils/tables.py, pgcli/packages/parseutils/utils.py, pgcli/pgcompleter.py, pgcli/pgexecute.py, requirements-dev.txt, setup.py
This reverts commit 59ae65cbbf698d1608e7fd3d55b507f3599ac117.
=> fix behave test, keep support for prompt-toolkit 2.x; lock prompt-toolkit==3.0.5 for test.

.travis.yml, setup.py, tests/features/steps/basic_commands.py, tox.ini
Python3.9 officially released!
=> test: test pgcli on python3.9

README.rst
=> doc: update the documentation for connection via SSL.

.github/workflows/ci.yml
=> Add 3.9 to build matrix.

.github/workflows/ci.yml
Trigger CI on pull request.
Same as https://github.com/dbcli/mycli/pull/934.
=> Trigger CI on pull request, not on push.

.github/workflows/ci.yml, tests/features/steps/basic_commands.py
This condition on black didn't really work.
=> Conditional didn't work in CI.

tests/utils.py
Fix for dbtests - they were broken since switching to GH Actions.
=> Postgres user has password in ci.

DEVELOP.rst, README.rst, pgcli/main.py
* removed obsolete links to gitter
* changed the status button in README from travis to github actions
=> Remove gitter links, update build status badge.

.pre-commit-config.yaml, changelog.rst, pgcli/main.py, pgcli/packages/pgliterals/pgliterals.json, pgcli/pgcompleter.py, tests/test_smart_completion_multiple_schemata.py, tests/utils.py
Include functions from search_path in completion.
=> Include functions from search_path in completion.

changelog.rst, pgcli/completion_refresher.py, pgcli/main.py, pgcli/pgexecute.py, tests/features/steps/specials.py, tests/features/steps/wrappers.py, tests/test_completion_refresher.py, tests/test_pgexecute.py
Make pgcli work with pgbouncer (about as well as psql does).
Attempt to fix #1093 .
=> Another attempt to fix pgbouncer error (1093.)

setup.py
Related pygments issue: https://github.com/pygments/pygments/issues/2027
=> Workaround pygments related issue.

pgcli/main.py, tests/test_ssh_tunnel.py
This PR goes on top of https://github.com/dbcli/pgcli/pull/1301. It adds a `ssh tunnels` config section where we can auto match a regex of the DB's host to an SSH tunnel url.
With this addition, there is truly no more need for a custom script to handle tunnels, pgcli can do it all (at least in my case 😁 ).
Of course, I'll add documentation if this gets merged!
=> Add auto matching for SSH tunnels

release.py, setup.py
Bump pgspecial to released 1.13.1.
=> Bump pgspecial.

changelog.rst
Changelog update before releasing 3.4.1.
=> Changelog update to release 3.4.1.

changelog.rst, pgcli/pgexecute.py, tests/test_pgexecute.py
=> Fix comments plus special - Issue #1362

changelog.rst
Changelog update to release 3.5.0.
=> Changelog update to release 3.5.0.

README.rst
Add maintainer contact info to readme.
=> Add maintainer contact info to readme

.github/workflows/ci.yml
rst2html command replaced with docutils.
=> rst2html -> docutils

README.rst
Fixes #1468.
- [-] I've added this contribution to the `changelog.rst`: not relevant
- [-] I've added my name to the `AUTHORS` file: I'm already there
=> readme: update link to pip installation guide
